In [1]:
import numpy as np 
import pandas as pd 
import ipaddress # For preprocesing ip adresses
import re # regular expression library will be used to extract values within brackets
from sklearn.preprocessing import MinMaxScaler # used to normalize continuous data in physical dataset

# I / Preprocessing

### 0- Concat and Merge compatibility

In [7]:
df1 = pd.read_csv('Network_dataset/csv/attack_1.csv')

In [9]:
df2 = pd.read_csv('Network_dataset/csv/attack_2.csv')

In [10]:
df3 = pd.read_csv('Network_dataset/csv/attack_3.csv')

In [11]:
df4 = pd.read_csv('Network_dataset/csv/attack_4.csv')

In [17]:
df_phy1 = pd.read_csv('Physical_dataset/phy_att_1.csv', encoding='utf-16', delimiter='\t')

In [18]:
df_phy2 = pd.read_csv('Physical_dataset/phy_att_2.csv', encoding='utf-16', delimiter='\t')

In [52]:
df_phy3 = pd.read_csv('Physical_dataset/phy_att_3.csv', encoding='utf-16', delimiter='\t')

In [66]:
df_phy4 = pd.read_csv('Physical_dataset/phy_att_4.csv')

In [11]:
df = pd.read_csv('super.csv')

Check the Time part where we will rearange them

### 1- Network Data

In [12]:
# Display features of out dataset
print(df.columns)

Index(['mac_s', 'mac_d', 'ip_s', 'ip_d', 'sport', 'dport', 'proto', 'flags',
       'size', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst', 'modbus_response',
       'Tank_1', 'Tank_2', 'Tank_3', 'Tank_4', 'Tank_5', 'Tank_6', 'Tank_7',
       'Tank_8', 'Pump_1', 'Pump_2', 'Pump_3', 'Pump_4', 'Pump_5', 'Pump_6',
       'Flow_sensor_1', 'Flow_sensor_2', 'Flow_sensor_3', 'Flow_sensor_4',
       'Valv_1', 'Valv_2', 'Valv_3', 'Valv_4', 'Valv_5', 'Valv_6', 'Valv_7',
       'Valv_8', 'Valv_9', 'Valv_10', 'Valv_11', 'Valv_12', 'Valv_13',
       'Valv_14', 'Valv_15', 'Valv_16', 'Valv_17', 'Valv_18', 'Valv_19',
       'Valv_20', 'Valv_21', 'Valv_22', 'Label'],
      dtype='object')

In [30]:
# Display all nan values per feature
print(df.isna().sum())

mac_s                    0
mac_d                    0
ip_s                   945
ip_d                   945
sport                22775
dport                22775
proto                    0
flags                22775
size                     0
modbus_fn           961018
n_pkt_src              945
n_pkt_dst              945
modbus_response    2348433
Tank_1                   0
Tank_2                   0
Tank_3                   0
Tank_4                   0
Tank_5                   0
Tank_6                   0
Tank_7                   0
Tank_8                   0
Pump_1                   0
Pump_2                   0
Pump_3                   0
Pump_4                   0
Pump_5                   0
Pump_6                   0
Flow_sensor_1            0
Flow_sensor_2            0
Flow_sensor_3            0
Flow_sensor_4            0
Valv_1                   0
Valv_2                   0
Valv_3                   0
Valv_4                   0
Valv_5                   0
Valv_6                   0
Valv_7                   0
Valv_8                   0
Valv_9                   0
Valv_10                  0
Valv_11                  0
Valv_12                  0
Valv_13                  0
Valv_14                  0
Valv_15                  0
Valv_16                  0
Valv_17                  0
Valv_18                  0
Valv_19                  0
Valv_20                  0
Valv_21                  0
Valv_22                  0
Label                    0
dtype: int64

In [31]:
# Iterate over each feature to print the number of unique values and the unique values themselves
for column in df.columns:
    unique_count = df[column].nunique(dropna=False)  # Set dropna=False to include NaN in the count if present
    unique_values = df[column].unique()
    
    print(f"Feature: {column}")
    print(f"Number of Unique Values: {unique_count}")
    print(f"Unique Values: {unique_values}\n")

Feature: mac_s
Number of Unique Values: 9
Unique Values: ['74:46:a0:bd:a7:1b' '0a:fe:ec:47:74:fb' 'fa:00:bc:90:d7:fa'
 'e6:3f:ac:c9:a8:8c' '00:80:f4:03:fb:12' 'fe:bb:16:7b:c3:27'
 '4a:35:83:e0:3d:a4' '00:0c:29:47:8c:22' '00:0c:29:47:8c:0e']

Feature: mac_d
Number of Unique Values: 10
Unique Values: ['0a:fe:ec:47:74:fb' 'e6:3f:ac:c9:a8:8c' 'fa:00:bc:90:d7:fa'
 '74:46:a0:bd:a7:1b' '00:80:f4:03:fb:12' 'fe:bb:16:7b:c3:27'
 '4a:35:83:e0:3d:a4' 'ff:ff:ff:ff:ff:ff' '00:0c:29:47:8c:22'
 '00:0c:29:47:8c:0e']

Feature: ip_s
Number of Unique Values: 9
Unique Values: ['84.3.251.20' '84.3.251.102' '84.3.251.103' '84.3.251.101' '84.3.251.18'
 '84.3.251.105' '84.3.251.104' nan '84.3.251.110']

Feature: ip_d
Number of Unique Values: 9
Unique Values: ['84.3.251.102' '84.3.251.101' '84.3.251.103' '84.3.251.20' '84.3.251.18'
 '84.3.251.105' '84.3.251.104' nan '84.3.251.110']

Feature: sport
Number of Unique Values: 65537
Unique Values: [56667. 56666. 56668. ...  1129.  1130.  1131.]

Feature: dport
Number of Unique Values: 18313
Unique Values: [  502. 56667. 56668. ... 16643. 16644. 16645.]

Feature: proto
Number of Unique Values: 5
Unique Values: ['Modbus' 'TCP' 'ARP' 'ICMP' 'IP']

Feature: flags
Number of Unique Values: 13
Unique Values: [1.100000e+04 1.000000e+01 1.001000e+04 1.000000e+04 1.000100e+04
 1.010000e+04 1.000000e+02          nan 1.100001e+07 1.100100e+04
 1.000000e+00 1.010010e+05 0.000000e+00]

Feature: size
Number of Unique Values: 54
Unique Values: [  66   64   65   74   78   77   60 1514 1433   62  590   70   82  109
   68   71   80   73  130   81   95  100   69  165   86  120   84  151
  122   92  133   88   87  104  146  115  144  173  129  316  317   83
   93  113  218  116  112  149  546   67   99  117  153   91]

Feature: modbus_fn
Number of Unique Values: 5
Unique Values: ['Read Coils Request' 'Read Coils Response' 'Read Holding Registers'
 'Read Holding Registers Response' nan]

Feature: n_pkt_src
Number of Unique Values: 102
Unique Values: [  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  nan  52.  53.  54.
  55.  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.
  69.  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.
  83.  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.
  97.  98.  99. 100.]

Feature: n_pkt_dst
Number of Unique Values: 102
Unique Values: [  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  nan  53.  54.
  55.  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.
  69.  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.
  83.  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.
  97.  98.  99. 100.]

Feature: modbus_response
Number of Unique Values: 3302
Unique Values: [nan '[0]' '[7]' ... '[2759]' '[2377]' '[2042]']

Feature: Tank_1
Number of Unique Values: 1796
Unique Values: [  0  54 162 ... 315 285 143]

Feature: Tank_2
Number of Unique Values: 1770
Unique Values: [  0  10  95 ... 311 563 651]

Feature: Tank_3
Number of Unique Values: 1681
Unique Values: [  0  18  94 ... 861 549 477]

Feature: Tank_4
Number of Unique Values: 1099
Unique Values: [  0  25  32 ... 458 842 909]

Feature: Tank_5
Number of Unique Values: 834
Unique Values: [  0  31  69 113 117 144 174 173 200 207 237 250 268 269 291 304 323 331
 336 360 362 374 375 401 414 437 444 452 471 478 495 516 515 522 531 546
 577 578 581 608 612 618 637 653 667 672 695 707 716 715 737 751 754 777
 780 797 811 818 812 808 803 799 795 790 787 782 778 772 768 764 759 748
 745 740 736 731 727 722 718 712 708 703 699 690 686 681 676 673 664 660
 655 651 646 643 638 634 628 625 623 616 613 609 604 600 597 592 588 584
 579 575 571 567 562 558 553 550 544 541 537 532 528 523 520 511 506 502
 499 493 491 486 482 477 474 468 465 461 457 447 443 439 435 430 426 422
 418 413 409 405 399 397 391 388 382 379 370 366 361 357 351 347 342 338
 335 329 326 321 316 311 307 302 297 292 288 284 278 273 264 258 254 248
 244 240 233 229 222 218 211 195 190 183 178 171 166 158 152 139 133 124
 107  99  87  77  61  47  29  18  12   8   7   6   4   2   1  26  80 114
 119 167 202 221 249 280 287 306 322 327 348 356 385 416 431 466 480 527
 552 587 589 633 645 665 687 693 706 713 753 765 758 767 805 814 825 824
 822 816 810 806 804 798 796 781 771 769 756 747 741 738 732 729 724 720
 710 702 698 689 684 677 668 663 659 652 647 644 641 636 632 627 624 619
 611 603 599 595 591 586 582 574 570 564 561 545 542 536 533 525 521 517
 513 508 501 497 492 489 484 472 469 464 460 455 440 432 427 423 419 415
 410 406 403 398 394 390 386 381 378 372 369 363 334 330 325 317 312 308
 303 299 293 290 276 271 267 261 257 251 247 242 238 232 227 223 217 212
 206 201 161 154 148 140 134 126 111 102  94  81  71  54  40  24  17   9
   5   3  35  85 121 132 157 176 197 208 263 279 298 365 393 424 448 458
 476 494 524 548 576 635 688 723 733 750 755 773 813 820 832 833 834 830
 821 817 763 725 711 680 640 615 610 607 590 569 565 540 512 504 488 479
 475 467 462 454 451 446 442 438 434 421 417 396 384 376 358 355 350 346
 340 337 332 328 319 315 310 301 282 272 265 245 239 235 225 220 214 198
 191 186 179 169 162 149 143 135 129 120 103  96  74  62  43  27  16  11
  68  95 160 320 367 387 598 622 656 704 779 792 826 809 800 791 783 774
 770 766 761 757 744 734 726 714 701 696 692 679 675 671 662 642 639 631
 626 614 606 594 573 549 529 496 470 456 450 402 364 294 289 285 270 266
 260 256 252 243 215 188 177 172 164 146 110  91  78  56  39 122 155 181
 199 219 230 313 333 383 483 530 551 572 670 717 835 827 823 819 801 793
 785 776 762 749 709 650 630 602 583 566 557 507 500 487 463 459 433 389
 380 371 341 324 283 275 255 216 210 205 194 182 175 170 163 153 131 115
 108  98  90  67  55  13  10  23 127 196 213 286 295 505 666 685 789 828
 802 752 691 683 674 661 657 629 620 617 605 580 568 560 555 543 535 526
 519 509 490 453 449 445 436 428 420 412 407 404 377 281 262 189 185 165
 159 147 141 101  93  72  42  28  36  89 151 184 411 425 514 658 678 697
 719 735 807 760 742 721 682 648 559 534 368 359 343 309  82  58  45  32
  14 168 226 353 485 775 786 669 554 538 481 274 246 193 138 100  52  38
  22  46 150 236 339 429 503 728 743 746 694 373 142  60  15 156 209 354
 784 836 837 838 829 831 654 601 593 539 518 473 392 345 318 314 277 259
 234 228 203  79  66  21 739 730 547 408 395 349 187 128  53  34 106 180
 224 585 649 621 510 352  73 563 498 400 145 125  64  51  20  37 344 788
 596 300 296  86 441 192 104  84  75  59  44  25 109 118  76 700 815 136
  30 705 556  92  19 112 137 231 794 130 123  97 305 241 204  63  50  88
  65  49  83  57 253 116]

Feature: Tank_6
Number of Unique Values: 533
Unique Values: [  0   9  16  25  29  38  46  50  58  67  72  78  86  94 100 109 116 121
 128 137 142 149 156 161 168 176 182 189 194 202 208 214 220 226 233 240
 246 252 258 266 272 277 284 290 297 304 310 316 322 329 335 342 348 355
 361 368 374 380 387 393 400 406 412 419 425 432 439 445 452 459 466 473
 479 486 493 501 507 515 521 529 536 543 550 558 565 572 580 588 597 606
 615 623 632 641 650 662 672 683 694 707 721 737 756 780 800 799 795 789
 774 766 758 751 736 727 719 703 695 687 671 663 655 639 631 614 598 582
 574 566 542 534 518 510 502 494 478 470 454 446 438 422 413 405 397 381
 373 365 357 349 333 325 317 309 293 285 261 253 245 237 229 212 204 196
 188 172 164 148 132 124 108  92  84  76  68  52  44  36  20  11   3   8
   4   6   7   5  10  13  18  15  26  39  49  43  37  14   1   2  23  30
  51  57  63  71  85  91  98 105 111 118 130 138 144 150 163 171 183 195
 200 207 213 219 225 231 238 251 257 263 270 276 283 289 295 302 308 314
 320 327 334 340 346 351 358 364 371 377 383 390 395 402 408 415 421 427
 433 440 447 448 450 437 435 434 423 411 404 403 394 392 382 367 360 362
 359 388 311 303 279 271 247 239 230 206 190 174 158 126 102  70  62  54
  12  35  41  60  74  79  88  95 101 107 115 127 134 140 146 153 159 166
 173 178 185 203 209 215 221 228 241 248 254 260 278 291 315 321 328 347
 353 372 378 384 409 416 428 441 453 460 458 456 455 443 431 420 410 407
 399 398 389 414 336 312 280 222 198 110  21  27  34  48  53  75  83  87
 141 160 191 205 211 217 223 235 255 267 273 287 300 307 341 366 391 429
 436 442 449 463 457 444 417 418 430 464 462 326 318 294 286 262 197 181
 165 133 125 117  93  77  69  61  45  17  40  73  81  99 113 120 147 154
 180 186 192 199 210 218 242 269 275 282 288 301 306 319 332 338 344 356
 363 376 426 379 375 369 345 330 298 274 250 234 201 193 177 169 145 129
  89  24  32  66 114 135 162 167 179 216 236 244 249 256 461 401 343 337
 313 305 281 265 136 104  96  64  56  59  80 155 232 354  19 103 123 184
 370 396 175 151 143 119  55  31 131 139 152 227 268 299 324 352 424 451
 385 350  42  90  97 106 112 386 187  47 467 465 122 170 331  65  33 292
 323  28 157 224 243 259  82  22 296 339 474]

Feature: Tank_7
Number of Unique Values: 102
Unique Values: [  0  16  24  40  48  64  72  88  96 112 120 136 144 160 168 184 192 209
 217 233 241 257 265 273 289 297 313 321 337 345 361 369 385 393 410 418
 426 442 450 458 466 402 377 353 329 305 281 249 225 176 128  80  32   8
  56 104 152 201 434 474 490 498 514 522 538 546 562 570 586 594 611 619
 635 643 659 667 683 691 707 715 731 739 755 763 779 787 804 812 771 747
 723 699 675 627 603 554 530 506 482 578 651 795]

Feature: Tank_8
Number of Unique Values: 493
Unique Values: [  0   8  16  24  32  40  48  56  64  72  80  88  96 104 112 120 128 136
 144 152 160 168 176 184 192 201 209 217 225 233 241 249 257 265 273 281
 289 297 305 313 321 329 337 345 353 357 365 373 375 383 384 392 393 401
 402 410 411 419 427 435 437 445 453 461 467 475 483 491 499 507 505 493
 492 490 488 486 484 482 480 479 465 456 454 451 450 448 447 444 442 441
 440 438 434 433 431 430 429 428 426 425 424 423 421 420 418 417 416 414
 413 412 409 408 407 406 405 404 403 400 399 398 397 396 395 394 391 390
 389 388 380 371 362 354 290 282 274 267 260 253 246 239 232 218 212 205
 199 186 180 174 163 157 151 146 140 135 130 125 115 110 106 101  92  84
  76  68  61  57  54  50  47  44  41  38  36  33  30  28  25  23  21  19
  17  15  13  12  10   9   7   6   5   4   3   2   1 361 369 415 464 472
 496 504 494 481 477 474 470 468 463 462 460 459 457 455 452 449 446 443
 439 366 358 349 341 333 325 317 309 301 293 285 278 270 263 256 242 235
 228 221 215 208 202 195 189 183 177 171 165 159 154 148 143 138 132 127
 122 117 108 103  98  94  90  86  81  77  73  70  66  62  59  55  52  49
  46  43  37  34  29  27  22  20  18  14  11  78 102 118 126 134 142 150
 158 166 182 190 198 206 214 222 231 247 255 271 279 287 295 303 311 319
 327 335 343 351 359 367 432  99  26  31  51  65  69  85 109 116 119 133
 139 141 149 156 161 167 169 172 173 175 179 181 185 187 194 196 197 204
 207 210 211 213 216 220 224 226 227 230 234 236 237 240 243 244 245 219
 200 193 147 131 121 111  97  93  58  42  39 370 378 386 497 495 489 487
 485 478 476 473 471 469 466 458 436 387 352 344 336 296 288 266 258 251
 191 145 129 124 114 105 100  91  87  83  79  75  71  67  60  53  35 377
 385 498 506 422 360 280 203 155  95  63 368 376 304 502 500 350 342 334
 326 318 310 302 294 286 264 250 229 178 123 113  82  74 501 374 382 503
 381 223 379 363 346 298 275 107 252 268 276 284 292 300 308 316 324 332
 340 348 356 364 372 355 338 330 322 314 306 283 261  45 347 323 331 339
 164 188 269 277 153 162 170]

Feature: Pump_1
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Pump_2
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Pump_3
Number of Unique Values: 1
Unique Values: [False]

Feature: Pump_4
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Pump_5
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Pump_6
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Flow_sensor_1
Number of Unique Values: 3
Unique Values: [   0 4000  100]

Feature: Flow_sensor_2
Number of Unique Values: 2
Unique Values: [   0 4000]

Feature: Flow_sensor_3
Number of Unique Values: 1
Unique Values: [0]

Feature: Flow_sensor_4
Number of Unique Values: 1343
Unique Values: [   0 4782 4772 ... 2042 1898 1706]

Feature: Valv_1
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_2
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_3
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_4
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_5
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_6
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_7
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_8
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_9
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_10
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_11
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_12
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_13
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_14
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_15
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_16
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_17
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_18
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_19
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_20
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_21
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_22
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Label
Number of Unique Values: 2
Unique Values: [0 1]

In [13]:
# Check for any -1 values across all features because later will be used to replace nan values and to reinforce the missing_pattern
print((df == -1).any().any())

# As you can see there is no single -1 value which will allow us to proceed as planned

False

In [14]:
# Clean column names by removing spaces that will later create errors in calls
df.columns = df.columns.str.replace(' ', '')

In [15]:
# set function using the ipadress library to transform ips to original decimal representation
def ip_to_int(ip):
    if pd.isna(ip):
        return -1  # in order to keep the nan values intact we replace it by -1 as we will do the same with all other nans
    return int(ipaddress.ip_address(ip))


# Apply the function to the IP address columns
df['ip_s'] = df['ip_s'].apply(ip_to_int)
df['ip_d'] = df['ip_d'].apply(ip_to_int)

In [16]:
# Factorize excluding -1 to keep our nan values remarkable as -1
def factorize_exclude_neg1(series):
    # Identify the values to be factorized (excluding -1)
    mask = series != -1
    
    # Factorize the masked values
    factorized_values, unique_values = pd.factorize(series[mask])
    
    # Create a full series with -1 preserved
    result = pd.Series(-1, index=series.index)
    result[mask] = factorized_values
    return result

# Apply the factorization while preserving -1
df['ip_s'] = factorize_exclude_neg1(df['ip_s'])
df['ip_d'] = factorize_exclude_neg1(df['ip_d'])

In [38]:
# as you can see nan values disappeared in ip_s and ip_d
print(df.isna().sum())

mac_s                     0
mac_d                     0
ip_s                      0
ip_d                      0
sport               4115050
dport               4115050
proto                     0
flags               4115050
size                      0
modbus_fn           5078450
n_pkt_src              1373
n_pkt_dst              1373
modbus_response    13319822
Tank_1                    0
Tank_2                    0
Tank_3                    0
Tank_4                    0
Tank_5                    0
Tank_6                    0
Tank_7                    0
Tank_8                    0
Pump_1                    0
Pump_2                    0
Pump_3                    0
Pump_4                    0
Pump_5                    0
Pump_6                    0
Flow_sensor_1             0
Flow_sensor_2             0
Flow_sensor_3             0
Flow_sensor_4             0
Valv_1                    0
Valv_2                    0
Valv_3                    0
Valv_4                    0
Valv_5                    0
Valv_6                    0
Valv_7                    0
Valv_8                    0
Valv_9                    0
Valv_10                   0
Valv_11                   0
Valv_12                   0
Valv_13                   0
Valv_14                   0
Valv_15                   0
Valv_16                   0
Valv_17                   0
Valv_18                   0
Valv_19                   0
Valv_20                   0
Valv_21                   0
Valv_22                   0
Label                     0
dtype: int64

In [39]:
# and here we ve got existence of -1  True since they replaced nan values in previous columns ip
print((df == -1).any().any())

True

In [17]:
# Drop the 'dport' column and keep 'sport' because of negative correlation and specialist advice
# The 'dport' and 'sport' columns are negatively correlated and often alternate values, introducing redundancy.
# retaining 'sport' because it is more valuable for detecting certain attacks
# where 'sport' might not receive a corresponding 'dport' response, making 'sport' crucial for identifying anomalies.
df = df.drop(columns=['dport'])

In [18]:
# Replace all nan values in the 'sport' column with -1
df['sport'] = df['sport'].fillna(-1)

In [19]:
# Replace all nan values in the 'flags' column with -1
df['flags'] = df['flags'].fillna(-1)

In [20]:
# Same goes for 'n_pkt_src' & 'n_pkt_dst' 
df['n_pkt_src'] = df['n_pkt_src'].fillna(-1)
df['n_pkt_dst'] = df['n_pkt_dst'].fillna(-1)

In [21]:
# Function to extract integers from brackets and also replace nan with -1 in modbus_response
def extract_int(value):
    if pd.isna(value):
        return -1  # Replace NaNs with -1
    match = re.search(r'\d+', str(value))
    if match:
        return int(match.group(0))
    return -1

# Apply the function to the 'modbus_response' column
df['modbus_response'] = df['modbus_response'].apply(extract_int)

In [22]:
# Function to factorize the mac_s and mac_d address columns and get unique values id's 
def factorize_mac_column(col):
    factorized_values, unique_values = pd.factorize(col)
    return factorized_values

# Apply the function to the MAC address columns
df['mac_s'] = factorize_mac_column(df['mac_s'])
df['mac_d'] = factorize_mac_column(df['mac_d'])

In [46]:
# as you can see now the only one remaining with nan values is modbus_fn which we will proceed next
print(df.isna().sum())

mac_s                    0
mac_d                    0
ip_s                     0
ip_d                     0
sport                    0
proto                    0
flags                    0
size                     0
modbus_fn          5078450
n_pkt_src                0
n_pkt_dst                0
modbus_response          0
Tank_1                   0
Tank_2                   0
Tank_3                   0
Tank_4                   0
Tank_5                   0
Tank_6                   0
Tank_7                   0
Tank_8                   0
Pump_1                   0
Pump_2                   0
Pump_3                   0
Pump_4                   0
Pump_5                   0
Pump_6                   0
Flow_sensor_1            0
Flow_sensor_2            0
Flow_sensor_3            0
Flow_sensor_4            0
Valv_1                   0
Valv_2                   0
Valv_3                   0
Valv_4                   0
Valv_5                   0
Valv_6                   0
Valv_7                   0
Valv_8                   0
Valv_9                   0
Valv_10                  0
Valv_11                  0
Valv_12                  0
Valv_13                  0
Valv_14                  0
Valv_15                  0
Valv_16                  0
Valv_17                  0
Valv_18                  0
Valv_19                  0
Valv_20                  0
Valv_21                  0
Valv_22                  0
Label                    0
dtype: int64

In [23]:
# Replace NaNs with a placeholder value for factorization
modbus_fn_temp = df['modbus_fn'].fillna('NaN_Placeholder')

# Factorize the column
factorized_values, unique_values = pd.factorize(modbus_fn_temp)

# Replace the placeholder with -1
factorized_values = np.where(modbus_fn_temp == 'NaN_Placeholder', -1, factorized_values)

# Add the processed column back to the DataFrame
df['modbus_fn'] = factorized_values

In [24]:
# Factorize the proto column
proto_factorized, proto_unique = pd.factorize(df['proto'])

# Overwrite column like we did in all previous ones
df['proto'] = proto_factorized

In [25]:
# Factorize the size column
size_factorized, size_unique = pd.factorize(df['size'])

# Overwrite column like we did in all previous ones
df['size'] = size_factorized

In [26]:
# Factorize the flags column that contains binary representation of flags, we transform them to simple binary representation
def factorize_flags(series):
    # Identify the values to be factorized (excluding -1)
    mask = series != -1
    
    # Factorize the masked values
    factorized_values, unique_values = pd.factorize(series[mask])
    
    # Create a full series with -1 preserved
    result = pd.Series(-1, index=series.index)
    result[mask] = factorized_values
    return result
df['flags'] = factorize_flags(df['flags'])

In [ ]:
# Drop Time feature since the packets are already organized by time corresponding their index 
df = df.drop(['Time'], axis=1)
# DO NOT EXE ALREADY TIMELESS DF

In [28]:
df['sport'] = df['sport'].astype(int)

df['n_pkt_src'] = df['n_pkt_src'].astype(int)

df['n_pkt_dst'] = df['n_pkt_dst'].astype(int)

In [53]:
# Let's again check uniqueness of each feature
for column in df.columns:
    unique_count = df[column].nunique(dropna=False)  
    unique_values = df[column].unique()
    
    print(f"Feature: {column}")
    print(f"Number of Unique Values: {unique_count}")
    print(f"Unique Values: {unique_values}\n")

Feature: mac_s
Number of Unique Values: 9
Unique Values: [0 1 2 3 4 5 6 7 8]

Feature: mac_d
Number of Unique Values: 10
Unique Values: [0 1 2 3 4 5 6 7 8 9]

Feature: ip_s
Number of Unique Values: 9
Unique Values: [ 0  1  2  3  4  5  6 -1  7]

Feature: ip_d
Number of Unique Values: 9
Unique Values: [ 0  1  2  3  4  5  6 -1  7]

Feature: sport
Number of Unique Values: 65537
Unique Values: [56667 56666 56668 ...  1129  1130  1131]

Feature: proto
Number of Unique Values: 5
Unique Values: [0 1 2 3 4]

Feature: flags
Number of Unique Values: 13
Unique Values: [ 0  1  2  3  4  5  6 -1  7  8  9 10 11]

Feature: size
Number of Unique Values: 54
Unique Values: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53]

Feature: modbus_fn
Number of Unique Values: 5
Unique Values: [ 0  1  2  3 -1]

Feature: n_pkt_src
Number of Unique Values: 102
Unique Values: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  -1  52
  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70
  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88
  89  90  91  92  93  94  95  96  97  98  99 100]

Feature: n_pkt_dst
Number of Unique Values: 102
Unique Values: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  -1
  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70
  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88
  89  90  91  92  93  94  95  96  97  98  99 100]

Feature: modbus_response
Number of Unique Values: 3302
Unique Values: [  -1    0    7 ... 2759 2377 2042]

Feature: Tank_1
Number of Unique Values: 1796
Unique Values: [  0  54 162 ... 315 285 143]

Feature: Tank_2
Number of Unique Values: 1770
Unique Values: [  0  10  95 ... 311 563 651]

Feature: Tank_3
Number of Unique Values: 1681
Unique Values: [  0  18  94 ... 861 549 477]

Feature: Tank_4
Number of Unique Values: 1099
Unique Values: [  0  25  32 ... 458 842 909]

Feature: Tank_5
Number of Unique Values: 834
Unique Values: [  0  31  69 113 117 144 174 173 200 207 237 250 268 269 291 304 323 331
 336 360 362 374 375 401 414 437 444 452 471 478 495 516 515 522 531 546
 577 578 581 608 612 618 637 653 667 672 695 707 716 715 737 751 754 777
 780 797 811 818 812 808 803 799 795 790 787 782 778 772 768 764 759 748
 745 740 736 731 727 722 718 712 708 703 699 690 686 681 676 673 664 660
 655 651 646 643 638 634 628 625 623 616 613 609 604 600 597 592 588 584
 579 575 571 567 562 558 553 550 544 541 537 532 528 523 520 511 506 502
 499 493 491 486 482 477 474 468 465 461 457 447 443 439 435 430 426 422
 418 413 409 405 399 397 391 388 382 379 370 366 361 357 351 347 342 338
 335 329 326 321 316 311 307 302 297 292 288 284 278 273 264 258 254 248
 244 240 233 229 222 218 211 195 190 183 178 171 166 158 152 139 133 124
 107  99  87  77  61  47  29  18  12   8   7   6   4   2   1  26  80 114
 119 167 202 221 249 280 287 306 322 327 348 356 385 416 431 466 480 527
 552 587 589 633 645 665 687 693 706 713 753 765 758 767 805 814 825 824
 822 816 810 806 804 798 796 781 771 769 756 747 741 738 732 729 724 720
 710 702 698 689 684 677 668 663 659 652 647 644 641 636 632 627 624 619
 611 603 599 595 591 586 582 574 570 564 561 545 542 536 533 525 521 517
 513 508 501 497 492 489 484 472 469 464 460 455 440 432 427 423 419 415
 410 406 403 398 394 390 386 381 378 372 369 363 334 330 325 317 312 308
 303 299 293 290 276 271 267 261 257 251 247 242 238 232 227 223 217 212
 206 201 161 154 148 140 134 126 111 102  94  81  71  54  40  24  17   9
   5   3  35  85 121 132 157 176 197 208 263 279 298 365 393 424 448 458
 476 494 524 548 576 635 688 723 733 750 755 773 813 820 832 833 834 830
 821 817 763 725 711 680 640 615 610 607 590 569 565 540 512 504 488 479
 475 467 462 454 451 446 442 438 434 421 417 396 384 376 358 355 350 346
 340 337 332 328 319 315 310 301 282 272 265 245 239 235 225 220 214 198
 191 186 179 169 162 149 143 135 129 120 103  96  74  62  43  27  16  11
  68  95 160 320 367 387 598 622 656 704 779 792 826 809 800 791 783 774
 770 766 761 757 744 734 726 714 701 696 692 679 675 671 662 642 639 631
 626 614 606 594 573 549 529 496 470 456 450 402 364 294 289 285 270 266
 260 256 252 243 215 188 177 172 164 146 110  91  78  56  39 122 155 181
 199 219 230 313 333 383 483 530 551 572 670 717 835 827 823 819 801 793
 785 776 762 749 709 650 630 602 583 566 557 507 500 487 463 459 433 389
 380 371 341 324 283 275 255 216 210 205 194 182 175 170 163 153 131 115
 108  98  90  67  55  13  10  23 127 196 213 286 295 505 666 685 789 828
 802 752 691 683 674 661 657 629 620 617 605 580 568 560 555 543 535 526
 519 509 490 453 449 445 436 428 420 412 407 404 377 281 262 189 185 165
 159 147 141 101  93  72  42  28  36  89 151 184 411 425 514 658 678 697
 719 735 807 760 742 721 682 648 559 534 368 359 343 309  82  58  45  32
  14 168 226 353 485 775 786 669 554 538 481 274 246 193 138 100  52  38
  22  46 150 236 339 429 503 728 743 746 694 373 142  60  15 156 209 354
 784 836 837 838 829 831 654 601 593 539 518 473 392 345 318 314 277 259
 234 228 203  79  66  21 739 730 547 408 395 349 187 128  53  34 106 180
 224 585 649 621 510 352  73 563 498 400 145 125  64  51  20  37 344 788
 596 300 296  86 441 192 104  84  75  59  44  25 109 118  76 700 815 136
  30 705 556  92  19 112 137 231 794 130 123  97 305 241 204  63  50  88
  65  49  83  57 253 116]

Feature: Tank_6
Number of Unique Values: 533
Unique Values: [  0   9  16  25  29  38  46  50  58  67  72  78  86  94 100 109 116 121
 128 137 142 149 156 161 168 176 182 189 194 202 208 214 220 226 233 240
 246 252 258 266 272 277 284 290 297 304 310 316 322 329 335 342 348 355
 361 368 374 380 387 393 400 406 412 419 425 432 439 445 452 459 466 473
 479 486 493 501 507 515 521 529 536 543 550 558 565 572 580 588 597 606
 615 623 632 641 650 662 672 683 694 707 721 737 756 780 800 799 795 789
 774 766 758 751 736 727 719 703 695 687 671 663 655 639 631 614 598 582
 574 566 542 534 518 510 502 494 478 470 454 446 438 422 413 405 397 381
 373 365 357 349 333 325 317 309 293 285 261 253 245 237 229 212 204 196
 188 172 164 148 132 124 108  92  84  76  68  52  44  36  20  11   3   8
   4   6   7   5  10  13  18  15  26  39  49  43  37  14   1   2  23  30
  51  57  63  71  85  91  98 105 111 118 130 138 144 150 163 171 183 195
 200 207 213 219 225 231 238 251 257 263 270 276 283 289 295 302 308 314
 320 327 334 340 346 351 358 364 371 377 383 390 395 402 408 415 421 427
 433 440 447 448 450 437 435 434 423 411 404 403 394 392 382 367 360 362
 359 388 311 303 279 271 247 239 230 206 190 174 158 126 102  70  62  54
  12  35  41  60  74  79  88  95 101 107 115 127 134 140 146 153 159 166
 173 178 185 203 209 215 221 228 241 248 254 260 278 291 315 321 328 347
 353 372 378 384 409 416 428 441 453 460 458 456 455 443 431 420 410 407
 399 398 389 414 336 312 280 222 198 110  21  27  34  48  53  75  83  87
 141 160 191 205 211 217 223 235 255 267 273 287 300 307 341 366 391 429
 436 442 449 463 457 444 417 418 430 464 462 326 318 294 286 262 197 181
 165 133 125 117  93  77  69  61  45  17  40  73  81  99 113 120 147 154
 180 186 192 199 210 218 242 269 275 282 288 301 306 319 332 338 344 356
 363 376 426 379 375 369 345 330 298 274 250 234 201 193 177 169 145 129
  89  24  32  66 114 135 162 167 179 216 236 244 249 256 461 401 343 337
 313 305 281 265 136 104  96  64  56  59  80 155 232 354  19 103 123 184
 370 396 175 151 143 119  55  31 131 139 152 227 268 299 324 352 424 451
 385 350  42  90  97 106 112 386 187  47 467 465 122 170 331  65  33 292
 323  28 157 224 243 259  82  22 296 339 474]

Feature: Tank_7
Number of Unique Values: 102
Unique Values: [  0  16  24  40  48  64  72  88  96 112 120 136 144 160 168 184 192 209
 217 233 241 257 265 273 289 297 313 321 337 345 361 369 385 393 410 418
 426 442 450 458 466 402 377 353 329 305 281 249 225 176 128  80  32   8
  56 104 152 201 434 474 490 498 514 522 538 546 562 570 586 594 611 619
 635 643 659 667 683 691 707 715 731 739 755 763 779 787 804 812 771 747
 723 699 675 627 603 554 530 506 482 578 651 795]

Feature: Tank_8
Number of Unique Values: 493
Unique Values: [  0   8  16  24  32  40  48  56  64  72  80  88  96 104 112 120 128 136
 144 152 160 168 176 184 192 201 209 217 225 233 241 249 257 265 273 281
 289 297 305 313 321 329 337 345 353 357 365 373 375 383 384 392 393 401
 402 410 411 419 427 435 437 445 453 461 467 475 483 491 499 507 505 493
 492 490 488 486 484 482 480 479 465 456 454 451 450 448 447 444 442 441
 440 438 434 433 431 430 429 428 426 425 424 423 421 420 418 417 416 414
 413 412 409 408 407 406 405 404 403 400 399 398 397 396 395 394 391 390
 389 388 380 371 362 354 290 282 274 267 260 253 246 239 232 218 212 205
 199 186 180 174 163 157 151 146 140 135 130 125 115 110 106 101  92  84
  76  68  61  57  54  50  47  44  41  38  36  33  30  28  25  23  21  19
  17  15  13  12  10   9   7   6   5   4   3   2   1 361 369 415 464 472
 496 504 494 481 477 474 470 468 463 462 460 459 457 455 452 449 446 443
 439 366 358 349 341 333 325 317 309 301 293 285 278 270 263 256 242 235
 228 221 215 208 202 195 189 183 177 171 165 159 154 148 143 138 132 127
 122 117 108 103  98  94  90  86  81  77  73  70  66  62  59  55  52  49
  46  43  37  34  29  27  22  20  18  14  11  78 102 118 126 134 142 150
 158 166 182 190 198 206 214 222 231 247 255 271 279 287 295 303 311 319
 327 335 343 351 359 367 432  99  26  31  51  65  69  85 109 116 119 133
 139 141 149 156 161 167 169 172 173 175 179 181 185 187 194 196 197 204
 207 210 211 213 216 220 224 226 227 230 234 236 237 240 243 244 245 219
 200 193 147 131 121 111  97  93  58  42  39 370 378 386 497 495 489 487
 485 478 476 473 471 469 466 458 436 387 352 344 336 296 288 266 258 251
 191 145 129 124 114 105 100  91  87  83  79  75  71  67  60  53  35 377
 385 498 506 422 360 280 203 155  95  63 368 376 304 502 500 350 342 334
 326 318 310 302 294 286 264 250 229 178 123 113  82  74 501 374 382 503
 381 223 379 363 346 298 275 107 252 268 276 284 292 300 308 316 324 332
 340 348 356 364 372 355 338 330 322 314 306 283 261  45 347 323 331 339
 164 188 269 277 153 162 170]

Feature: Pump_1
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Pump_2
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Pump_3
Number of Unique Values: 1
Unique Values: [False]

Feature: Pump_4
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Pump_5
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Pump_6
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Flow_sensor_1
Number of Unique Values: 3
Unique Values: [   0 4000  100]

Feature: Flow_sensor_2
Number of Unique Values: 2
Unique Values: [   0 4000]

Feature: Flow_sensor_3
Number of Unique Values: 1
Unique Values: [0]

Feature: Flow_sensor_4
Number of Unique Values: 1343
Unique Values: [   0 4782 4772 ... 2042 1898 1706]

Feature: Valv_1
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_2
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_3
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_4
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_5
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_6
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_7
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_8
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_9
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_10
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_11
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_12
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_13
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_14
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_15
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_16
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_17
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_18
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_19
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_20
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_21
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_22
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Label
Number of Unique Values: 2
Unique Values: [0 1]

In [29]:
# Features that contain missing values and that will be used to construct missing_pattern feature
print([col for col in df.columns if (df[col] == -1).any()])

['ip_s', 'ip_d', 'sport', 'flags', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst', 'modbus_response']

In [30]:
# Function to create a binary string for the missingness pattern
def create_missing_pattern(row, columns):
    binary_string = ''.join(['1' if row[col] == -1 else '0' for col in columns])
    return int(binary_string, 2)

# list of columns with nan values
list_nan_cols = ['ip_s', 'ip_d', 'sport', 'flags', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst', 'modbus_response']

# Apply the function to create the missing_pattern column
df['missing_pattern'] = df.apply(create_missing_pattern, columns=list_nan_cols, axis=1)

In [56]:
# Let's again check uniqueness of each feature
for column in df.columns:
    unique_count = df[column].nunique(dropna=False)  
    unique_values = df[column].unique()
    
    print(f"Feature: {column}")
    print(f"Number of Unique Values: {unique_count}")
    print(f"Unique Values: {unique_values}\n")
    

# Here we notice that the uniqueness of missing_pattern is only 5 which is pretty fascinating :

# Pattern: 0, Binary: 00000000, Missing Columns: (No missing values)

# Pattern: 1, Binary: 00000001, Missing Columns: (1 column missing, modbus_response)

# Pattern: 9, Binary: 00001001, Missing Columns: (2 columns missing, ip_s and modbus_response)

# Pattern: 57, Binary: 00111001, Missing Columns: (5 columns missing, ip_s, flags, modbus_fn, n_pkt_src, modbus_response)

# Pattern: 255, Binary: 11111111, Missing Columns: (All 8 columns missing)

Feature: mac_s
Number of Unique Values: 9
Unique Values: [0 1 2 3 4 5 6 7 8]

Feature: mac_d
Number of Unique Values: 10
Unique Values: [0 1 2 3 4 5 6 7 8 9]

Feature: ip_s
Number of Unique Values: 9
Unique Values: [ 0  1  2  3  4  5  6 -1  7]

Feature: ip_d
Number of Unique Values: 9
Unique Values: [ 0  1  2  3  4  5  6 -1  7]

Feature: sport
Number of Unique Values: 65537
Unique Values: [56667 56666 56668 ...  1129  1130  1131]

Feature: proto
Number of Unique Values: 5
Unique Values: [0 1 2 3 4]

Feature: flags
Number of Unique Values: 13
Unique Values: [ 0  1  2  3  4  5  6 -1  7  8  9 10 11]

Feature: size
Number of Unique Values: 54
Unique Values: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53]

Feature: modbus_fn
Number of Unique Values: 5
Unique Values: [ 0  1  2  3 -1]

Feature: n_pkt_src
Number of Unique Values: 102
Unique Values: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  -1  52
  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70
  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88
  89  90  91  92  93  94  95  96  97  98  99 100]

Feature: n_pkt_dst
Number of Unique Values: 102
Unique Values: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  -1
  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70
  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88
  89  90  91  92  93  94  95  96  97  98  99 100]

Feature: modbus_response
Number of Unique Values: 3302
Unique Values: [  -1    0    7 ... 2759 2377 2042]

Feature: Tank_1
Number of Unique Values: 1796
Unique Values: [  0  54 162 ... 315 285 143]

Feature: Tank_2
Number of Unique Values: 1770
Unique Values: [  0  10  95 ... 311 563 651]

Feature: Tank_3
Number of Unique Values: 1681
Unique Values: [  0  18  94 ... 861 549 477]

Feature: Tank_4
Number of Unique Values: 1099
Unique Values: [  0  25  32 ... 458 842 909]

Feature: Tank_5
Number of Unique Values: 834
Unique Values: [  0  31  69 113 117 144 174 173 200 207 237 250 268 269 291 304 323 331
 336 360 362 374 375 401 414 437 444 452 471 478 495 516 515 522 531 546
 577 578 581 608 612 618 637 653 667 672 695 707 716 715 737 751 754 777
 780 797 811 818 812 808 803 799 795 790 787 782 778 772 768 764 759 748
 745 740 736 731 727 722 718 712 708 703 699 690 686 681 676 673 664 660
 655 651 646 643 638 634 628 625 623 616 613 609 604 600 597 592 588 584
 579 575 571 567 562 558 553 550 544 541 537 532 528 523 520 511 506 502
 499 493 491 486 482 477 474 468 465 461 457 447 443 439 435 430 426 422
 418 413 409 405 399 397 391 388 382 379 370 366 361 357 351 347 342 338
 335 329 326 321 316 311 307 302 297 292 288 284 278 273 264 258 254 248
 244 240 233 229 222 218 211 195 190 183 178 171 166 158 152 139 133 124
 107  99  87  77  61  47  29  18  12   8   7   6   4   2   1  26  80 114
 119 167 202 221 249 280 287 306 322 327 348 356 385 416 431 466 480 527
 552 587 589 633 645 665 687 693 706 713 753 765 758 767 805 814 825 824
 822 816 810 806 804 798 796 781 771 769 756 747 741 738 732 729 724 720
 710 702 698 689 684 677 668 663 659 652 647 644 641 636 632 627 624 619
 611 603 599 595 591 586 582 574 570 564 561 545 542 536 533 525 521 517
 513 508 501 497 492 489 484 472 469 464 460 455 440 432 427 423 419 415
 410 406 403 398 394 390 386 381 378 372 369 363 334 330 325 317 312 308
 303 299 293 290 276 271 267 261 257 251 247 242 238 232 227 223 217 212
 206 201 161 154 148 140 134 126 111 102  94  81  71  54  40  24  17   9
   5   3  35  85 121 132 157 176 197 208 263 279 298 365 393 424 448 458
 476 494 524 548 576 635 688 723 733 750 755 773 813 820 832 833 834 830
 821 817 763 725 711 680 640 615 610 607 590 569 565 540 512 504 488 479
 475 467 462 454 451 446 442 438 434 421 417 396 384 376 358 355 350 346
 340 337 332 328 319 315 310 301 282 272 265 245 239 235 225 220 214 198
 191 186 179 169 162 149 143 135 129 120 103  96  74  62  43  27  16  11
  68  95 160 320 367 387 598 622 656 704 779 792 826 809 800 791 783 774
 770 766 761 757 744 734 726 714 701 696 692 679 675 671 662 642 639 631
 626 614 606 594 573 549 529 496 470 456 450 402 364 294 289 285 270 266
 260 256 252 243 215 188 177 172 164 146 110  91  78  56  39 122 155 181
 199 219 230 313 333 383 483 530 551 572 670 717 835 827 823 819 801 793
 785 776 762 749 709 650 630 602 583 566 557 507 500 487 463 459 433 389
 380 371 341 324 283 275 255 216 210 205 194 182 175 170 163 153 131 115
 108  98  90  67  55  13  10  23 127 196 213 286 295 505 666 685 789 828
 802 752 691 683 674 661 657 629 620 617 605 580 568 560 555 543 535 526
 519 509 490 453 449 445 436 428 420 412 407 404 377 281 262 189 185 165
 159 147 141 101  93  72  42  28  36  89 151 184 411 425 514 658 678 697
 719 735 807 760 742 721 682 648 559 534 368 359 343 309  82  58  45  32
  14 168 226 353 485 775 786 669 554 538 481 274 246 193 138 100  52  38
  22  46 150 236 339 429 503 728 743 746 694 373 142  60  15 156 209 354
 784 836 837 838 829 831 654 601 593 539 518 473 392 345 318 314 277 259
 234 228 203  79  66  21 739 730 547 408 395 349 187 128  53  34 106 180
 224 585 649 621 510 352  73 563 498 400 145 125  64  51  20  37 344 788
 596 300 296  86 441 192 104  84  75  59  44  25 109 118  76 700 815 136
  30 705 556  92  19 112 137 231 794 130 123  97 305 241 204  63  50  88
  65  49  83  57 253 116]

Feature: Tank_6
Number of Unique Values: 533
Unique Values: [  0   9  16  25  29  38  46  50  58  67  72  78  86  94 100 109 116 121
 128 137 142 149 156 161 168 176 182 189 194 202 208 214 220 226 233 240
 246 252 258 266 272 277 284 290 297 304 310 316 322 329 335 342 348 355
 361 368 374 380 387 393 400 406 412 419 425 432 439 445 452 459 466 473
 479 486 493 501 507 515 521 529 536 543 550 558 565 572 580 588 597 606
 615 623 632 641 650 662 672 683 694 707 721 737 756 780 800 799 795 789
 774 766 758 751 736 727 719 703 695 687 671 663 655 639 631 614 598 582
 574 566 542 534 518 510 502 494 478 470 454 446 438 422 413 405 397 381
 373 365 357 349 333 325 317 309 293 285 261 253 245 237 229 212 204 196
 188 172 164 148 132 124 108  92  84  76  68  52  44  36  20  11   3   8
   4   6   7   5  10  13  18  15  26  39  49  43  37  14   1   2  23  30
  51  57  63  71  85  91  98 105 111 118 130 138 144 150 163 171 183 195
 200 207 213 219 225 231 238 251 257 263 270 276 283 289 295 302 308 314
 320 327 334 340 346 351 358 364 371 377 383 390 395 402 408 415 421 427
 433 440 447 448 450 437 435 434 423 411 404 403 394 392 382 367 360 362
 359 388 311 303 279 271 247 239 230 206 190 174 158 126 102  70  62  54
  12  35  41  60  74  79  88  95 101 107 115 127 134 140 146 153 159 166
 173 178 185 203 209 215 221 228 241 248 254 260 278 291 315 321 328 347
 353 372 378 384 409 416 428 441 453 460 458 456 455 443 431 420 410 407
 399 398 389 414 336 312 280 222 198 110  21  27  34  48  53  75  83  87
 141 160 191 205 211 217 223 235 255 267 273 287 300 307 341 366 391 429
 436 442 449 463 457 444 417 418 430 464 462 326 318 294 286 262 197 181
 165 133 125 117  93  77  69  61  45  17  40  73  81  99 113 120 147 154
 180 186 192 199 210 218 242 269 275 282 288 301 306 319 332 338 344 356
 363 376 426 379 375 369 345 330 298 274 250 234 201 193 177 169 145 129
  89  24  32  66 114 135 162 167 179 216 236 244 249 256 461 401 343 337
 313 305 281 265 136 104  96  64  56  59  80 155 232 354  19 103 123 184
 370 396 175 151 143 119  55  31 131 139 152 227 268 299 324 352 424 451
 385 350  42  90  97 106 112 386 187  47 467 465 122 170 331  65  33 292
 323  28 157 224 243 259  82  22 296 339 474]

Feature: Tank_7
Number of Unique Values: 102
Unique Values: [  0  16  24  40  48  64  72  88  96 112 120 136 144 160 168 184 192 209
 217 233 241 257 265 273 289 297 313 321 337 345 361 369 385 393 410 418
 426 442 450 458 466 402 377 353 329 305 281 249 225 176 128  80  32   8
  56 104 152 201 434 474 490 498 514 522 538 546 562 570 586 594 611 619
 635 643 659 667 683 691 707 715 731 739 755 763 779 787 804 812 771 747
 723 699 675 627 603 554 530 506 482 578 651 795]

Feature: Tank_8
Number of Unique Values: 493
Unique Values: [  0   8  16  24  32  40  48  56  64  72  80  88  96 104 112 120 128 136
 144 152 160 168 176 184 192 201 209 217 225 233 241 249 257 265 273 281
 289 297 305 313 321 329 337 345 353 357 365 373 375 383 384 392 393 401
 402 410 411 419 427 435 437 445 453 461 467 475 483 491 499 507 505 493
 492 490 488 486 484 482 480 479 465 456 454 451 450 448 447 444 442 441
 440 438 434 433 431 430 429 428 426 425 424 423 421 420 418 417 416 414
 413 412 409 408 407 406 405 404 403 400 399 398 397 396 395 394 391 390
 389 388 380 371 362 354 290 282 274 267 260 253 246 239 232 218 212 205
 199 186 180 174 163 157 151 146 140 135 130 125 115 110 106 101  92  84
  76  68  61  57  54  50  47  44  41  38  36  33  30  28  25  23  21  19
  17  15  13  12  10   9   7   6   5   4   3   2   1 361 369 415 464 472
 496 504 494 481 477 474 470 468 463 462 460 459 457 455 452 449 446 443
 439 366 358 349 341 333 325 317 309 301 293 285 278 270 263 256 242 235
 228 221 215 208 202 195 189 183 177 171 165 159 154 148 143 138 132 127
 122 117 108 103  98  94  90  86  81  77  73  70  66  62  59  55  52  49
  46  43  37  34  29  27  22  20  18  14  11  78 102 118 126 134 142 150
 158 166 182 190 198 206 214 222 231 247 255 271 279 287 295 303 311 319
 327 335 343 351 359 367 432  99  26  31  51  65  69  85 109 116 119 133
 139 141 149 156 161 167 169 172 173 175 179 181 185 187 194 196 197 204
 207 210 211 213 216 220 224 226 227 230 234 236 237 240 243 244 245 219
 200 193 147 131 121 111  97  93  58  42  39 370 378 386 497 495 489 487
 485 478 476 473 471 469 466 458 436 387 352 344 336 296 288 266 258 251
 191 145 129 124 114 105 100  91  87  83  79  75  71  67  60  53  35 377
 385 498 506 422 360 280 203 155  95  63 368 376 304 502 500 350 342 334
 326 318 310 302 294 286 264 250 229 178 123 113  82  74 501 374 382 503
 381 223 379 363 346 298 275 107 252 268 276 284 292 300 308 316 324 332
 340 348 356 364 372 355 338 330 322 314 306 283 261  45 347 323 331 339
 164 188 269 277 153 162 170]

Feature: Pump_1
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Pump_2
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Pump_3
Number of Unique Values: 1
Unique Values: [False]

Feature: Pump_4
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Pump_5
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Pump_6
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Flow_sensor_1
Number of Unique Values: 3
Unique Values: [   0 4000  100]

Feature: Flow_sensor_2
Number of Unique Values: 2
Unique Values: [   0 4000]

Feature: Flow_sensor_3
Number of Unique Values: 1
Unique Values: [0]

Feature: Flow_sensor_4
Number of Unique Values: 1343
Unique Values: [   0 4782 4772 ... 2042 1898 1706]

Feature: Valv_1
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_2
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_3
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_4
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_5
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_6
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_7
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_8
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_9
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_10
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_11
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_12
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_13
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_14
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_15
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_16
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_17
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_18
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_19
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_20
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_21
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_22
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Label
Number of Unique Values: 2
Unique Values: [0 1]

Feature: missing_pattern
Number of Unique Values: 5
Unique Values: [  1   0   9 255  57]

In [31]:
df.head()

,mac_s,mac_d,ip_s,ip_d,sport,proto,flags,size,modbus_fn,n_pkt_src,...,Valv_15,Valv_16,Valv_17,Valv_18,Valv_19,Valv_20,Valv_21,Valv_22,Label,missing_pattern
0,0,0,0,0,56667,0,0,0,0,0,...,False,False,False,False,False,False,False,False,0,1
1,0,1,0,1,56666,0,0,0,0,1,...,False,False,False,False,False,False,False,False,0,1
2,0,2,0,2,56668,0,0,0,0,2,...,False,False,False,False,False,False,False,False,0,1
3,1,3,1,3,502,0,0,1,1,0,...,False,False,False,False,False,False,False,False,0,0
4,2,3,2,3,502,0,0,1,1,0,...,False,False,False,False,False,False,False,False,0,0

In [32]:
# CHECKPOINT 

# Go see Prepro and Embedding 
df.to_csv('super_checkpoint.csv', index=False)

In [33]:
# We rearranged the order of features in order to give meaning to the new engineered feature 'missing_pattern'.
# This feature was created to capture patterns of NaNs in the dataset.
# By arranging the columns in a specific order, the 'missing_pattern' feature generates a binary value following that order,
# which is then converted to a decimal number, giving each pattern a unique identifier.

new_col_order= ['ip_s', 'ip_d', 'sport', 'flags', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst', 
                'modbus_response', 'missing_pattern', 'mac_s', 'mac_d', 'proto', 'size',
                'Tank_1', 'Tank_2', 'Tank_3', 'Tank_4', 'Tank_5', 'Tank_6', 'Tank_7',
       'Tank_8', 'Pump_1', 'Pump_2', 'Pump_3', 'Pump_4', 'Pump_5', 'Pump_6',
       'Flow_sensor_1', 'Flow_sensor_2', 'Flow_sensor_3', 'Flow_sensor_4',
       'Valv_1', 'Valv_2', 'Valv_3', 'Valv_4', 'Valv_5', 'Valv_6', 'Valv_7',
       'Valv_8', 'Valv_9', 'Valv_10', 'Valv_11', 'Valv_12', 'Valv_13',
       'Valv_14', 'Valv_15', 'Valv_16', 'Valv_17', 'Valv_18', 'Valv_19',
       'Valv_20', 'Valv_21', 'Valv_22', 'Label']

df = df[new_col_order]

In [34]:
print(df.head())

   ip_s  ip_d  sport  flags  modbus_fn  n_pkt_src  n_pkt_dst  modbus_response  \
0     0     0  56667      0          0          0          0               -1
1     0     1  56666      0          0          1          0               -1
2     0     2  56668      0          0          2          0               -1
3     1     3    502      0          1          0          0                0
4     2     3    502      0          1          0          1                0

   missing_pattern  mac_s  ...  Valv_14  Valv_15  Valv_16  Valv_17  Valv_18  \
0                1      0  ...    False    False    False    False    False
1                1      0  ...    False    False    False    False    False
2                1      0  ...    False    False    False    False    False
3                0      1  ...    False    False    False    False    False
4                0      2  ...    False    False    False    False    False

   Valv_19  Valv_20  Valv_21  Valv_22  Label
0    False    False    False    False      0
1    False    False    False    False      0
2    False    False    False    False      0
3    False    False    False    False      0
4    False    False    False    False      0

[5 rows x 54 columns]

### 2- Physical Data

In [35]:
# Display features of out dataset
print(df.columns)

Index(['ip_s', 'ip_d', 'sport', 'flags', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst',
       'modbus_response', 'missing_pattern', 'mac_s', 'mac_d', 'proto', 'size',
       'Tank_1', 'Tank_2', 'Tank_3', 'Tank_4', 'Tank_5', 'Tank_6', 'Tank_7',
       'Tank_8', 'Pump_1', 'Pump_2', 'Pump_3', 'Pump_4', 'Pump_5', 'Pump_6',
       'Flow_sensor_1', 'Flow_sensor_2', 'Flow_sensor_3', 'Flow_sensor_4',
       'Valv_1', 'Valv_2', 'Valv_3', 'Valv_4', 'Valv_5', 'Valv_6', 'Valv_7',
       'Valv_8', 'Valv_9', 'Valv_10', 'Valv_11', 'Valv_12', 'Valv_13',
       'Valv_14', 'Valv_15', 'Valv_16', 'Valv_17', 'Valv_18', 'Valv_19',
       'Valv_20', 'Valv_21', 'Valv_22', 'Label'],
      dtype='object')

In [36]:
# Display all nan values per feature
print(df.isna().sum())

# We notice no nan values from the plcs data

ip_s               0
ip_d               0
sport              0
flags              0
modbus_fn          0
n_pkt_src          0
n_pkt_dst          0
modbus_response    0
missing_pattern    0
mac_s              0
mac_d              0
proto              0
size               0
Tank_1             0
Tank_2             0
Tank_3             0
Tank_4             0
Tank_5             0
Tank_6             0
Tank_7             0
Tank_8             0
Pump_1             0
Pump_2             0
Pump_3             0
Pump_4             0
Pump_5             0
Pump_6             0
Flow_sensor_1      0
Flow_sensor_2      0
Flow_sensor_3      0
Flow_sensor_4      0
Valv_1             0
Valv_2             0
Valv_3             0
Valv_4             0
Valv_5             0
Valv_6             0
Valv_7             0
Valv_8             0
Valv_9             0
Valv_10            0
Valv_11            0
Valv_12            0
Valv_13            0
Valv_14            0
Valv_15            0
Valv_16            0
Valv_17            0
Valv_18            0
Valv_19            0
Valv_20            0
Valv_21            0
Valv_22            0
Label              0
dtype: int64

In [61]:
# Clean column names by removing spaces that will later create errors in calls
df.columns = df.columns.str.replace(' ', '')

In [37]:
# Convert boolean features to binary 
boolean_features = df.select_dtypes(include=['bool']).columns.tolist()
continuous_features = ['Tank_1', 'Tank_2', 'Tank_3', 'Tank_4', 'Tank_5', 'Tank_6', 'Tank_7',
                       'Tank_8', 'Flow_sensor_1', 'Flow_sensor_2', 'Flow_sensor_3', 'Flow_sensor_4']
df[boolean_features] = df[boolean_features].astype(int)

In [38]:
print('boolean features :',boolean_features)
print('continuous features :',continuous_features)

boolean features : ['Pump_1', 'Pump_2', 'Pump_3', 'Pump_4', 'Pump_5', 'Pump_6', 'Valv_1', 'Valv_2', 'Valv_3', 'Valv_4', 'Valv_5', 'Valv_6', 'Valv_7', 'Valv_8', 'Valv_9', 'Valv_10', 'Valv_11', 'Valv_12', 'Valv_13', 'Valv_14', 'Valv_15', 'Valv_16', 'Valv_17', 'Valv_18', 'Valv_19', 'Valv_20', 'Valv_21', 'Valv_22']
continuous features : ['Tank_1', 'Tank_2', 'Tank_3', 'Tank_4', 'Tank_5', 'Tank_6', 'Tank_7', 'Tank_8', 'Flow_sensor_1', 'Flow_sensor_2', 'Flow_sensor_3', 'Flow_sensor_4']

In [39]:
# Now all our features are int except for label multiclass
print(df.dtypes)

ip_s               int64
ip_d               int64
sport              int64
flags              int64
modbus_fn          int64
n_pkt_src          int64
n_pkt_dst          int64
modbus_response    int64
missing_pattern    int64
mac_s              int64
mac_d              int64
proto              int64
size               int64
Tank_1             int64
Tank_2             int64
Tank_3             int64
Tank_4             int64
Tank_5             int64
Tank_6             int64
Tank_7             int64
Tank_8             int64
Pump_1             int64
Pump_2             int64
Pump_3             int64
Pump_4             int64
Pump_5             int64
Pump_6             int64
Flow_sensor_1      int64
Flow_sensor_2      int64
Flow_sensor_3      int64
Flow_sensor_4      int64
Valv_1             int64
Valv_2             int64
Valv_3             int64
Valv_4             int64
Valv_5             int64
Valv_6             int64
Valv_7             int64
Valv_8             int64
Valv_9             int64
Valv_10            int64
Valv_11            int64
Valv_12            int64
Valv_13            int64
Valv_14            int64
Valv_15            int64
Valv_16            int64
Valv_17            int64
Valv_18            int64
Valv_19            int64
Valv_20            int64
Valv_21            int64
Valv_22            int64
Label              int64
dtype: object

In [37]:
# Now we extract the continious features to perform normalize them    # DO NOT EXE !!

# List of all features
all_features = df.columns.tolist()

# Continuous features by excluding boolean features
continuous_features = [feature for feature in all_features if feature not in boolean_features]

# Get rid of Time and Label_n and Label
continuous_features = continuous_features[1:-2]

In [40]:
# Initialize the MinMaxScaler to normalize cont data
scaler = MinMaxScaler()

# Normalize the continuous features
df[continuous_features] = scaler.fit_transform(df[continuous_features])

In [41]:
# Let's again check uniqueness of each feature
for column in df.columns:
    unique_count = df[column].nunique(dropna=False)  
    unique_values = df[column].unique()
    
    print(f"Feature: {column}")
    print(f"Number of Unique Values: {unique_count}")
    print(f"Unique Values: {unique_values}\n")

Feature: ip_s
Number of Unique Values: 9
Unique Values: [ 0  1  2  3  4  5  6 -1  7]

Feature: ip_d
Number of Unique Values: 9
Unique Values: [ 0  1  2  3  4  5  6 -1  7]

Feature: sport
Number of Unique Values: 65537
Unique Values: [56667 56666 56668 ...  1129  1130  1131]

Feature: flags
Number of Unique Values: 13
Unique Values: [ 0  1  2  3  4  5  6 -1  7  8  9 10 11]

Feature: modbus_fn
Number of Unique Values: 5
Unique Values: [ 0  1  2  3 -1]

Feature: n_pkt_src
Number of Unique Values: 102
Unique Values: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  -1  52
  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70
  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88
  89  90  91  92  93  94  95  96  97  98  99 100]

Feature: n_pkt_dst
Number of Unique Values: 102
Unique Values: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  -1
  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70
  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88
  89  90  91  92  93  94  95  96  97  98  99 100]

Feature: modbus_response
Number of Unique Values: 3302
Unique Values: [  -1    0    7 ... 2759 2377 2042]

Feature: missing_pattern
Number of Unique Values: 5
Unique Values: [  1   0   9 255  57]

Feature: mac_s
Number of Unique Values: 9
Unique Values: [0 1 2 3 4 5 6 7 8]

Feature: mac_d
Number of Unique Values: 10
Unique Values: [0 1 2 3 4 5 6 7 8 9]

Feature: proto
Number of Unique Values: 5
Unique Values: [0 1 2 3 4]

Feature: size
Number of Unique Values: 54
Unique Values: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53]

Feature: Tank_1
Number of Unique Values: 1796
Unique Values: [0.         0.02671945 0.08015834 ... 0.15586343 0.1410193  0.07075705]

Feature: Tank_2
Number of Unique Values: 1770
Unique Values: [0.         0.00497018 0.0472167  ... 0.15457256 0.27982107 0.32355865]

Feature: Tank_3
Number of Unique Values: 1681
Unique Values: [0.         0.00525241 0.02742924 ... 0.25124015 0.16019842 0.13918879]

Feature: Tank_4
Number of Unique Values: 1099
Unique Values: [0.         0.01982554 0.02537669 ... 0.36320381 0.66772403 0.72085646]

Feature: Tank_5
Number of Unique Values: 834
Unique Values: [0.         0.03699284 0.0823389  0.13484487 0.13961814 0.17183771
 0.20763723 0.20644391 0.23866348 0.24701671 0.28281623 0.29832936
 0.31980907 0.32100239 0.34725537 0.3627685  0.38544153 0.39498807
 0.40095465 0.42959427 0.43198091 0.44630072 0.44749403 0.47852029
 0.49403341 0.52147971 0.52983294 0.53937947 0.56205251 0.57040573
 0.59069212 0.61575179 0.61455847 0.62291169 0.63365155 0.65155131
 0.68854415 0.68973747 0.69331742 0.72553699 0.73031026 0.73747017
 0.7601432  0.77923628 0.79594272 0.80190931 0.82935561 0.84367542
 0.85441527 0.85322196 0.87947494 0.89618138 0.89976134 0.92720764
 0.93078759 0.95107399 0.96778043 0.97613365 0.96897375 0.96420048
 0.95823389 0.95346062 0.94868735 0.94272076 0.93914081 0.93317422
 0.92840095 0.92124105 0.91646778 0.91169451 0.90572792 0.89260143
 0.88902148 0.88305489 0.87828162 0.87231504 0.86754177 0.86157518
 0.85680191 0.849642   0.84486874 0.83890215 0.83412888 0.82338902
 0.81861575 0.81264916 0.80668258 0.80310263 0.79236277 0.7875895
 0.78162291 0.77684964 0.77088305 0.7673031  0.76133652 0.75656325
 0.74940334 0.74582339 0.74343675 0.73508353 0.73150358 0.72673031
 0.72076372 0.71599045 0.7124105  0.70644391 0.70167064 0.69689737
 0.69093079 0.68615752 0.68138425 0.67661098 0.67064439 0.66587112
 0.65990453 0.65632458 0.64916468 0.64558473 0.64081146 0.63484487
 0.6300716  0.62410501 0.62052506 0.6097852  0.60381862 0.59904535
 0.59546539 0.58830549 0.58591885 0.57995227 0.575179   0.56921241
 0.56563246 0.55847255 0.5548926  0.55011933 0.54534606 0.53341289
 0.52863962 0.52386635 0.51909308 0.51312649 0.50835322 0.50357995
 0.49880668 0.4928401  0.48806683 0.48329356 0.47613365 0.47374702
 0.46658711 0.46300716 0.45584726 0.4522673  0.44152745 0.43675418
 0.43078759 0.42601432 0.41885442 0.41408115 0.40811456 0.40334129
 0.39976134 0.39260143 0.38902148 0.38305489 0.37708831 0.37112172
 0.36634845 0.36038186 0.35441527 0.34844869 0.34367542 0.33890215
 0.33174224 0.32577566 0.3150358  0.30787589 0.30310263 0.29594272
 0.29116945 0.28639618 0.27804296 0.27326969 0.26491647 0.2601432
 0.25178998 0.2326969  0.22673031 0.21837709 0.2124105  0.20405728
 0.19809069 0.18854415 0.18138425 0.16587112 0.15871122 0.14797136
 0.12768496 0.11813842 0.10381862 0.09188544 0.07279236 0.05608592
 0.03460621 0.02147971 0.01431981 0.00954654 0.00835322 0.0071599
 0.00477327 0.00238663 0.00119332 0.03102625 0.09546539 0.13603819
 0.14200477 0.19928401 0.24105012 0.26372315 0.29713604 0.33412888
 0.3424821  0.36515513 0.38424821 0.3902148  0.41527446 0.424821
 0.45942721 0.49642005 0.51431981 0.55608592 0.57279236 0.62887828
 0.65871122 0.70047733 0.70286396 0.75536993 0.76968974 0.79355609
 0.81980907 0.82696897 0.8424821  0.85083532 0.89856802 0.91288783
 0.90453461 0.91527446 0.96062053 0.97136038 0.98448687 0.98329356
 0.98090692 0.97374702 0.96658711 0.96181384 0.95942721 0.9522673
 0.94988067 0.93198091 0.92004773 0.9176611  0.90214797 0.89140811
 0.88424821 0.88066826 0.87350835 0.8699284  0.86396181 0.85918854
 0.84725537 0.83770883 0.83293556 0.8221957  0.81622912 0.80787589
 0.79713604 0.79116945 0.78639618 0.77804296 0.77207637 0.76849642
 0.76491647 0.75894988 0.75417661 0.74821002 0.74463007 0.73866348
 0.72911695 0.71957041 0.71479714 0.71002387 0.7052506  0.69928401
 0.69451074 0.6849642  0.68019093 0.67303103 0.66945107 0.650358
 0.64677804 0.63961814 0.63603819 0.62649165 0.62171838 0.61694511
 0.61217184 0.60620525 0.59785203 0.59307876 0.58711217 0.58353222
 0.57756563 0.56324582 0.55966587 0.55369928 0.54892601 0.54295943
 0.52505967 0.51551313 0.50954654 0.50477327 0.5        0.49522673
 0.48926014 0.48448687 0.48090692 0.47494033 0.47016706 0.46539379
 0.46062053 0.45465394 0.45107399 0.44391408 0.44033413 0.43317422
 0.39856802 0.39379475 0.38782816 0.37828162 0.37231504 0.36754177
 0.36157518 0.35680191 0.349642   0.34606205 0.32935561 0.32338902
 0.31861575 0.31145585 0.30668258 0.29952267 0.2947494  0.28878282
 0.28400955 0.27684964 0.27088305 0.26610979 0.25894988 0.25298329
 0.24582339 0.2398568  0.19212411 0.18377088 0.17661098 0.16706444
 0.15990453 0.150358   0.13245823 0.12171838 0.11217184 0.09665871
 0.08472554 0.06443914 0.0477327  0.02863962 0.0202864  0.01073986
 0.00596659 0.00357995 0.04176611 0.10143198 0.14439141 0.1575179
 0.18735084 0.21002387 0.23508353 0.24821002 0.31384248 0.33293556
 0.35560859 0.43556086 0.46897375 0.50596659 0.53460621 0.54653938
 0.56801909 0.58949881 0.62529833 0.65393795 0.68735084 0.75775656
 0.82100239 0.8627685  0.87470167 0.89498807 0.90095465 0.92243437
 0.97016706 0.97852029 0.9928401  0.99403341 0.99522673 0.99045346
 0.9797136  0.97494033 0.91050119 0.86515513 0.84844869 0.81145585
 0.76372315 0.73389021 0.72792363 0.72434368 0.70405728 0.67899761
 0.67422434 0.64439141 0.61097852 0.60143198 0.5823389  0.57159905
 0.56682578 0.55727924 0.55131265 0.54176611 0.53818616 0.53221957
 0.5274463  0.52267303 0.51789976 0.50238663 0.49761337 0.4725537
 0.45823389 0.44868735 0.42720764 0.42362768 0.4176611  0.41288783
 0.40572792 0.40214797 0.39618138 0.39140811 0.38066826 0.37589499
 0.3699284  0.35918854 0.33651551 0.32458234 0.31622912 0.29236277
 0.28520286 0.28042959 0.26849642 0.26252983 0.25536993 0.23627685
 0.22792363 0.22195704 0.21360382 0.20167064 0.19331742 0.1778043
 0.17064439 0.16109785 0.15393795 0.14319809 0.12291169 0.11455847
 0.08830549 0.07398568 0.05131265 0.03221957 0.01909308 0.01312649
 0.08114558 0.11336516 0.19093079 0.38186158 0.43794749 0.46181384
 0.71360382 0.74224344 0.78281623 0.84009547 0.92959427 0.9451074
 0.98568019 0.96539379 0.95465394 0.94391408 0.93436754 0.92362768
 0.91885442 0.91408115 0.90811456 0.90334129 0.88782816 0.87589499
 0.86634845 0.85202864 0.83651551 0.83054893 0.82577566 0.81026253
 0.80548926 0.80071599 0.78997613 0.76610979 0.76252983 0.75298329
 0.74701671 0.7326969  0.72315036 0.70883055 0.68377088 0.65513126
 0.63126492 0.59188544 0.56085919 0.54415274 0.53699284 0.4797136
 0.43436754 0.35083532 0.34486874 0.34009547 0.3221957  0.31742243
 0.31026253 0.30548926 0.30071599 0.28997613 0.25656325 0.22434368
 0.21121718 0.2052506  0.19570406 0.17422434 0.13126492 0.10859189
 0.09307876 0.06682578 0.04653938 0.14558473 0.1849642  0.21599045
 0.23747017 0.26133652 0.27446301 0.37350835 0.3973747  0.45704057
 0.57637232 0.63245823 0.6575179  0.68257757 0.79952267 0.85560859
 0.99642005 0.98687351 0.98210024 0.97732697 0.95584726 0.94630072
 0.93675418 0.92601432 0.90930788 0.89379475 0.84606205 0.77565632
 0.75178998 0.71837709 0.69570406 0.67541766 0.6646778  0.60501193
 0.59665871 0.58114558 0.55250597 0.5477327  0.51670644 0.46420048
 0.45346062 0.44272076 0.40692124 0.38663484 0.33770883 0.32816229
 0.30429594 0.25775656 0.25059666 0.24463007 0.23150358 0.21718377
 0.20883055 0.20286396 0.19451074 0.18257757 0.15632458 0.1372315
 0.12887828 0.11694511 0.10739857 0.07995227 0.06563246 0.01551313
 0.01193317 0.0274463  0.15155131 0.23389021 0.25417661 0.34128878
 0.35202864 0.6026253  0.7947494  0.81742243 0.94152745 0.98806683
 0.95704057 0.8973747  0.82458234 0.8150358  0.80429594 0.78878282
 0.78400955 0.75059666 0.7398568  0.73627685 0.72195704 0.69212411
 0.6778043  0.66825776 0.66229117 0.64797136 0.63842482 0.62768496
 0.61933174 0.60739857 0.58472554 0.54057279 0.53579952 0.53102625
 0.5202864  0.51073986 0.50119332 0.49164678 0.48568019 0.48210024
 0.44988067 0.3353222  0.31264916 0.22553699 0.22076372 0.19689737
 0.18973747 0.17541766 0.16825776 0.12052506 0.11097852 0.08591885
 0.05011933 0.03341289 0.04295943 0.10620525 0.18019093 0.21957041
 0.49045346 0.5071599  0.61336516 0.78520286 0.80906921 0.83174224
 0.85799523 0.87708831 0.96300716 0.90692124 0.88544153 0.86038186
 0.81384248 0.77326969 0.66706444 0.6372315  0.43914081 0.42840095
 0.40930788 0.36873508 0.09785203 0.06921241 0.05369928 0.03818616
 0.01670644 0.20047733 0.26968974 0.42124105 0.57875895 0.924821
 0.93794749 0.79832936 0.66109785 0.64200477 0.57398568 0.32696897
 0.29355609 0.23031026 0.1646778  0.11933174 0.06205251 0.04534606
 0.02625298 0.0548926  0.17899761 0.28162291 0.40453461 0.51193317
 0.60023866 0.86873508 0.88663484 0.8902148  0.82816229 0.4451074
 0.16945107 0.07159905 0.01789976 0.18615752 0.24940334 0.42243437
 0.93556086 0.99761337 0.99880668 1.         0.98926014 0.99164678
 0.78042959 0.71718377 0.70763723 0.64319809 0.61813842 0.56443914
 0.46778043 0.41169451 0.37947494 0.37470167 0.33054893 0.30906921
 0.27923628 0.27207637 0.24224344 0.09427208 0.07875895 0.02505967
 0.88186158 0.87112172 0.65274463 0.48687351 0.47136038 0.41646778
 0.22315036 0.15274463 0.06324582 0.04057279 0.12649165 0.21479714
 0.2673031  0.69809069 0.77446301 0.74105012 0.60859189 0.42004773
 0.08711217 0.67183771 0.59427208 0.47732697 0.17303103 0.14916468
 0.07637232 0.06085919 0.02386635 0.04415274 0.41050119 0.94033413
 0.71121718 0.35799523 0.35322196 0.1026253  0.52625298 0.22911695
 0.12410501 0.10023866 0.08949881 0.07040573 0.05250597 0.02983294
 0.1300716  0.14081146 0.09069212 0.8353222  0.9725537  0.16229117
 0.03579952 0.84128878 0.66348449 0.1097852  0.02267303 0.13365155
 0.16348449 0.27565632 0.94749403 0.15513126 0.14677804 0.11575179
 0.36396181 0.2875895  0.24343675 0.075179   0.05966587 0.10501193
 0.07756563 0.05847255 0.09904535 0.06801909 0.30190931 0.13842482]

Feature: Tank_6
Number of Unique Values: 533
Unique Values: [0.      0.01125 0.02    0.03125 0.03625 0.0475  0.0575  0.0625  0.0725
 0.08375 0.09    0.0975  0.1075  0.1175  0.125   0.13625 0.145   0.15125
 0.16    0.17125 0.1775  0.18625 0.195   0.20125 0.21    0.22    0.2275
 0.23625 0.2425  0.2525  0.26    0.2675  0.275   0.2825  0.29125 0.3
 0.3075  0.315   0.3225  0.3325  0.34    0.34625 0.355   0.3625  0.37125
 0.38    0.3875  0.395   0.4025  0.41125 0.41875 0.4275  0.435   0.44375
 0.45125 0.46    0.4675  0.475   0.48375 0.49125 0.5     0.5075  0.515
 0.52375 0.53125 0.54    0.54875 0.55625 0.565   0.57375 0.5825  0.59125
 0.59875 0.6075  0.61625 0.62625 0.63375 0.64375 0.65125 0.66125 0.67
 0.67875 0.6875  0.6975  0.70625 0.715   0.725   0.735   0.74625 0.7575
 0.76875 0.77875 0.79    0.80125 0.8125  0.8275  0.84    0.85375 0.8675
 0.88375 0.90125 0.92125 0.945   0.975   1.      0.99875 0.99375 0.98625
 0.9675  0.9575  0.9475  0.93875 0.92    0.90875 0.89875 0.87875 0.86875
 0.85875 0.83875 0.82875 0.81875 0.79875 0.78875 0.7675  0.7475  0.7275
 0.7175  0.7075  0.6775  0.6675  0.6475  0.6375  0.6275  0.6175  0.5975
 0.5875  0.5675  0.5575  0.5475  0.5275  0.51625 0.50625 0.49625 0.47625
 0.46625 0.45625 0.44625 0.43625 0.41625 0.40625 0.39625 0.38625 0.36625
 0.35625 0.32625 0.31625 0.30625 0.29625 0.28625 0.265   0.255   0.245
 0.235   0.215   0.205   0.185   0.165   0.155   0.135   0.115   0.105
 0.095   0.085   0.065   0.055   0.045   0.025   0.01375 0.00375 0.01
 0.005   0.0075  0.00875 0.00625 0.0125  0.01625 0.0225  0.01875 0.0325
 0.04875 0.06125 0.05375 0.04625 0.0175  0.00125 0.0025  0.02875 0.0375
 0.06375 0.07125 0.07875 0.08875 0.10625 0.11375 0.1225  0.13125 0.13875
 0.1475  0.1625  0.1725  0.18    0.1875  0.20375 0.21375 0.22875 0.24375
 0.25    0.25875 0.26625 0.27375 0.28125 0.28875 0.2975  0.31375 0.32125
 0.32875 0.3375  0.345   0.35375 0.36125 0.36875 0.3775  0.385   0.3925
 0.4     0.40875 0.4175  0.425   0.4325  0.43875 0.4475  0.455   0.46375
 0.47125 0.47875 0.4875  0.49375 0.5025  0.51    0.51875 0.52625 0.53375
 0.54125 0.55    0.55875 0.56    0.5625  0.54625 0.54375 0.5425  0.52875
 0.51375 0.505   0.50375 0.4925  0.49    0.4775  0.45875 0.45    0.4525
 0.44875 0.485   0.38875 0.37875 0.34875 0.33875 0.30875 0.29875 0.2875
 0.2575  0.2375  0.2175  0.1975  0.1575  0.1275  0.0875  0.0775  0.0675
 0.015   0.04375 0.05125 0.075   0.0925  0.09875 0.11    0.11875 0.12625
 0.13375 0.14375 0.15875 0.1675  0.175   0.1825  0.19125 0.19875 0.2075
 0.21625 0.2225  0.23125 0.25375 0.26125 0.26875 0.27625 0.285   0.30125
 0.31    0.3175  0.325   0.3475  0.36375 0.39375 0.40125 0.41    0.43375
 0.44125 0.465   0.4725  0.48    0.51125 0.52    0.535   0.55125 0.56625
 0.575   0.5725  0.57    0.56875 0.55375 0.53875 0.525   0.5125  0.50875
 0.49875 0.4975  0.48625 0.5175  0.42    0.39    0.35    0.2775  0.2475
 0.1375  0.02625 0.03375 0.0425  0.06    0.06625 0.09375 0.10375 0.10875
 0.17625 0.2     0.23875 0.25625 0.26375 0.27125 0.27875 0.29375 0.31875
 0.33375 0.34125 0.35875 0.375   0.38375 0.42625 0.4575  0.48875 0.53625
 0.545   0.5525  0.56125 0.57875 0.57125 0.555   0.52125 0.5225  0.5375
 0.58    0.5775  0.4075  0.3975  0.3675  0.3575  0.3275  0.24625 0.22625
 0.20625 0.16625 0.15625 0.14625 0.11625 0.09625 0.08625 0.07625 0.05625
 0.02125 0.05    0.09125 0.10125 0.12375 0.14125 0.15    0.18375 0.1925
 0.225   0.2325  0.24    0.24875 0.2625  0.2725  0.3025  0.33625 0.34375
 0.3525  0.36    0.37625 0.3825  0.39875 0.415   0.4225  0.43    0.445
 0.45375 0.47    0.5325  0.47375 0.46875 0.46125 0.43125 0.4125  0.3725
 0.3425  0.3125  0.2925  0.25125 0.24125 0.22125 0.21125 0.18125 0.16125
 0.11125 0.03    0.04    0.0825  0.1425  0.16875 0.2025  0.20875 0.22375
 0.27    0.295   0.305   0.31125 0.32    0.57625 0.50125 0.42875 0.42125
 0.39125 0.38125 0.35125 0.33125 0.17    0.13    0.12    0.08    0.07
 0.07375 0.1     0.19375 0.29    0.4425  0.02375 0.12875 0.15375 0.23
 0.4625  0.495   0.21875 0.18875 0.17875 0.14875 0.06875 0.03875 0.16375
 0.17375 0.19    0.28375 0.335   0.37375 0.405   0.44    0.53    0.56375
 0.48125 0.4375  0.0525  0.1125  0.12125 0.1325  0.14    0.4825  0.23375
 0.05875 0.58375 0.58125 0.1525  0.2125  0.41375 0.08125 0.04125 0.365
 0.40375 0.035   0.19625 0.28    0.30375 0.32375 0.1025  0.0275  0.37
 0.42375 0.5925 ]

Feature: Tank_7
Number of Unique Values: 102
Unique Values: [0.         0.01970443 0.02955665 0.04926108 0.0591133  0.07881773
 0.08866995 0.10837438 0.1182266  0.13793103 0.14778325 0.16748768
 0.1773399  0.19704433 0.20689655 0.22660099 0.2364532  0.25738916
 0.26724138 0.28694581 0.29679803 0.31650246 0.32635468 0.3362069
 0.35591133 0.36576355 0.38546798 0.3953202  0.41502463 0.42487685
 0.44458128 0.4544335  0.47413793 0.48399015 0.50492611 0.51477833
 0.52463054 0.54433498 0.55418719 0.56403941 0.57389163 0.49507389
 0.46428571 0.43472906 0.40517241 0.37561576 0.34605911 0.30665025
 0.2770936  0.21674877 0.15763547 0.09852217 0.03940887 0.00985222
 0.06896552 0.12807882 0.18719212 0.24753695 0.53448276 0.58374384
 0.60344828 0.61330049 0.63300493 0.64285714 0.66256158 0.67241379
 0.69211823 0.70197044 0.72167488 0.73152709 0.75246305 0.76231527
 0.7820197  0.79187192 0.81157635 0.82142857 0.841133   0.85098522
 0.87068966 0.88054187 0.90024631 0.91009852 0.92980296 0.93965517
 0.95935961 0.96921182 0.99014778 1.         0.94950739 0.91995074
 0.89039409 0.86083744 0.83128079 0.77216749 0.74261084 0.68226601
 0.65270936 0.62315271 0.59359606 0.71182266 0.80172414 0.97906404]

Feature: Tank_8
Number of Unique Values: 493
Unique Values: [0.         0.01577909 0.03155819 0.04733728 0.06311637 0.07889546
 0.09467456 0.11045365 0.12623274 0.14201183 0.15779093 0.17357002
 0.18934911 0.20512821 0.2209073  0.23668639 0.25246548 0.26824458
 0.28402367 0.29980276 0.31558185 0.33136095 0.34714004 0.36291913
 0.37869822 0.3964497  0.4122288  0.42800789 0.44378698 0.45956607
 0.47534517 0.49112426 0.50690335 0.52268245 0.53846154 0.55424063
 0.57001972 0.58579882 0.60157791 0.617357   0.63313609 0.64891519
 0.66469428 0.68047337 0.69625247 0.70414201 0.7199211  0.7357002
 0.73964497 0.75542406 0.75739645 0.77317554 0.77514793 0.79092702
 0.79289941 0.8086785  0.81065089 0.82642998 0.84220907 0.85798817
 0.86193294 0.87771203 0.89349112 0.90927022 0.92110454 0.93688363
 0.95266272 0.96844181 0.98422091 1.         0.99605523 0.97238659
 0.9704142  0.96646943 0.96252465 0.95857988 0.95463511 0.95069034
 0.94674556 0.94477318 0.91715976 0.89940828 0.89546351 0.88954635
 0.88757396 0.88362919 0.8816568  0.87573964 0.87179487 0.86982249
 0.8678501  0.86390533 0.85601578 0.85404339 0.85009862 0.84812623
 0.84615385 0.84418146 0.84023669 0.8382643  0.83629191 0.83431953
 0.83037475 0.82840237 0.82445759 0.82248521 0.82051282 0.81656805
 0.81459566 0.81262327 0.80670611 0.80473373 0.80276134 0.80078895
 0.79881657 0.79684418 0.79487179 0.78895464 0.78698225 0.78500986
 0.78303748 0.78106509 0.7790927  0.77712032 0.77120316 0.76923077
 0.76725838 0.765286   0.7495069  0.73175542 0.71400394 0.69822485
 0.57199211 0.55621302 0.54043393 0.52662722 0.51282051 0.49901381
 0.4852071  0.47140039 0.45759369 0.42998028 0.41814596 0.40433925
 0.39250493 0.36686391 0.35502959 0.34319527 0.32149901 0.30966469
 0.29783037 0.28796844 0.27613412 0.26627219 0.25641026 0.24654832
 0.22682446 0.21696252 0.20907298 0.19921105 0.18145957 0.16568047
 0.14990138 0.13412229 0.12031558 0.11242604 0.10650888 0.09861933
 0.09270217 0.08678501 0.08086785 0.07495069 0.07100592 0.06508876
 0.0591716  0.05522682 0.04930966 0.04536489 0.04142012 0.03747535
 0.03353057 0.0295858  0.02564103 0.02366864 0.01972387 0.01775148
 0.01380671 0.01183432 0.00986193 0.00788955 0.00591716 0.00394477
 0.00197239 0.71203156 0.72781065 0.81854043 0.91518738 0.93096647
 0.97830375 0.99408284 0.97435897 0.94871795 0.9408284  0.93491124
 0.9270217  0.92307692 0.91321499 0.9112426  0.90729783 0.90532544
 0.90138067 0.8974359  0.89151874 0.88560158 0.87968442 0.87376726

In [42]:
# CHECKPOINT 

# Go see Prepro and Embedding 
df.to_csv('super_checkpoint.csv', index=False)

In [2]:
# load the checkpoint due to crashing kernel
df = pd.read_csv('super_checkpoint.csv')

### 3- Embedding Network Categorical Data

In [3]:
import torch
import torch.nn as nn

In [4]:
# Separate cat features and cont features and labels and drop them
features = df.drop(columns=['Tank_1', 'Tank_2', 'Tank_3', 'Tank_4', 'Tank_5', 'Tank_6',
       'Tank_7', 'Tank_8', 'Pump_1', 'Pump_2', 'Pump_3', 'Pump_4', 'Pump_5',
       'Pump_6', 'Flow_sensor_1', 'Flow_sensor_2', 'Flow_sensor_3',
       'Flow_sensor_4', 'Valv_1', 'Valv_2', 'Valv_3', 'Valv_4', 'Valv_5',
       'Valv_6', 'Valv_7', 'Valv_8', 'Valv_9', 'Valv_10', 'Valv_11', 'Valv_12',
       'Valv_13', 'Valv_14', 'Valv_15', 'Valv_16', 'Valv_17', 'Valv_18',
       'Valv_19', 'Valv_20', 'Valv_21', 'Valv_22','Label'])

In [5]:
features.columns

Index(['ip_s', 'ip_d', 'sport', 'flags', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst',
       'modbus_response', 'missing_pattern', 'mac_s', 'mac_d', 'proto',
       'size'],
      dtype='object')

In [6]:
# Checking if dim has been altered due to error in dimension during embedding
print(np.shape(features))
#print(np.shape(features.values))
#print(np.shape(features_tensor))

(21561878, 13)

In [5]:
# Add 1 to the columns that contain -1 to move away from negative because embedding processes positive only
list_nan_cols = ['ip_s', 'ip_d', 'sport', 'flags', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst', 'modbus_response']
for column in list_nan_cols:
    if (features[column] == -1).any():
        features[column] += 1

In [49]:
# Let's again check uniqueness of each feature for us to gather it data for embedding
for column in features.columns:
    unique_count = features[column].nunique(dropna=False)  
    unique_values = features[column].unique()
    
    print(f"Feature: {column}")
    print(f"Number of Unique Values: {unique_count}")
    print(f"Unique Values: {unique_values}\n")
    
# as we notice  -1 disappeared lettign place to 0

Feature: ip_s
Number of Unique Values: 9
Unique Values: [1 2 3 4 5 6 7 0 8]

Feature: ip_d
Number of Unique Values: 9
Unique Values: [1 2 3 4 5 6 7 0 8]

Feature: sport
Number of Unique Values: 65537
Unique Values: [56668 56667 56669 ...  1130  1131  1132]

Feature: flags
Number of Unique Values: 13
Unique Values: [ 1  2  3  4  5  6  7  0  8  9 10 11 12]

Feature: modbus_fn
Number of Unique Values: 5
Unique Values: [1 2 3 4 0]

Feature: n_pkt_src
Number of Unique Values: 102
Unique Values: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52   0  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101]

Feature: n_pkt_dst
Number of Unique Values: 102
Unique Values: [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53   0
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101]

Feature: modbus_response
Number of Unique Values: 3302
Unique Values: [   0    1    8 ... 2760 2378 2043]

Feature: missing_pattern
Number of Unique Values: 5
Unique Values: [  1   0   9 255  57]

Feature: mac_s
Number of Unique Values: 9
Unique Values: [0 1 2 3 4 5 6 7 8]

Feature: mac_d
Number of Unique Values: 10
Unique Values: [0 1 2 3 4 5 6 7 8 9]

Feature: proto
Number of Unique Values: 5
Unique Values: [0 1 2 3 4]

Feature: size
Number of Unique Values: 54
Unique Values: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53]

In [6]:
# Determine the number of unique values for each feature
unique_counts = features.nunique()

# Define embedding sizes based on uniqueness or what we rather call rule of thumb
embedding_sizes = [(unique, min(50, unique // 2)) for unique in unique_counts]

In [51]:
# make sure that uniqueness list is correct and involves features only
print(unique_counts)

ip_s                   9
ip_d                   9
sport              65537
flags                 13
modbus_fn              5
n_pkt_src            102
n_pkt_dst            102
modbus_response     3302
missing_pattern        5
mac_s                  9
mac_d                 10
proto                  5
size                  54
dtype: int64

In [9]:
# Make sure the embedding mapping is correct
print(embedding_sizes)
print(len(embedding_sizes))

#features['sport'].max()

[(9, 4), (9, 4), (65537, 50), (13, 6), (5, 2), (102, 50), (102, 50), (3302, 50), (5, 2), (9, 4), (10, 5), (5, 2), (54, 27)]
13

In [7]:
# THIS BLOCK TRANSFORMS VALUES TO MATCH MAX TO UNIQUENESS, because we might have uniquenes sof 8000 and max value of 65000 like in sport which wiill
# give problem when embedding
def factorize_sport(series):
    # Identify the values to be factorized (excluding -1)
    mask = series != -1
    
    # Factorize the masked values
    factorized_values, unique_values = pd.factorize(series[mask])
    
    # Create a full series with -1 preserved
    result = pd.Series(-1, index=series.index)
    result[mask] = factorized_values
    return result
features['sport'] = factorize_sport(features['sport'])

In [8]:
#  THIS BLOCK TRANSFORMS VALUES TO MATCH MAX TO UNIQUENESS, same for modbus_resp
def factorize_modbus_response(series):
    # Identify the values to be factorized (excluding -1)
    mask = series != -1
    
    # Factorize the masked values
    factorized_values, unique_values = pd.factorize(series[mask])
    
    # Create a full series with -1 preserved
    result = pd.Series(-1, index=series.index)
    result[mask] = factorized_values
    return result
features['modbus_response'] = factorize_modbus_response(features['modbus_response'])

In [9]:
#  THIS BLOCK TRANSFORMS VALUES TO MATCH MAX TO UNIQUENESS, same for missing pattern, although here i have a question
# here the unique values of this feature exp 255 and 57 are decimal from binaries that represents missing patterns
# accomodating their uniqueness to thier max might result into info loss or more complicated pattern to catch by model
# Thats why in our case and in case of bad results we will set it back to original and augment embedding output foir this feature to 50 instead of 2
# current : [5,2]   change next : [5,50] because of that 255 value
# Factorize the missing_pattern column
missing_pattern_factorized, missing_pattern_unique = pd.factorize(features['missing_pattern'])

# Overwrite column like we did in all previous ones
features['missing_pattern'] = missing_pattern_factorized

In [13]:
#  THIS BLOCK TRANSFORMS VALUES TO MATCH MAX TO UNIQUENESS, same drill
print(features['sport'].max())
print(features['modbus_response'].max())
print(features['missing_pattern'].max())

# as we can see those 3 features gave us problems during embedding due to their max value surpassing, now they re cool, 
# compare them to uniquenss must be lower

65536
3301
4

In [10]:
# Convert features to tensor on order for it to be computed correctly to embeddings
features_tensor = torch.tensor(features.values, dtype=torch.long)

In [11]:
len(features_tensor)

21561878

In [12]:
# Create an embedding layer for each feature and concatenate the embeddings to conserve the same order on the dataset
class EmbeddingNet(nn.Module):
    def __init__(self, embedding_sizes):
        super(EmbeddingNet, self).__init__()
        self.embeddings = nn.ModuleList([nn.Embedding(input_dim, output_dim) for input_dim, output_dim in embedding_sizes])
    
    def forward(self, x):
        embedded_features = []
        for i, embedding in enumerate(self.embeddings):
            # Check the shape and values of x[:, i]
            print(f"Processing feature {i} with shape {x[:, i].shape} and values: {x[:, i]}")
            
            # Ensure that no value in x[:, i] exceeds the embedding's input dimension
            max_index = torch.max(x[:, i]).item()
            min_index = torch.min(x[:, i]).item()
            input_dim = embedding.num_embeddings
            print(f"Feature {i}: min index {min_index}, max index {max_index}, input_dim {input_dim}")
            if max_index >= input_dim or min_index < 0:
                raise ValueError(f"Feature {i} has an index {min_index}-{max_index} out of range for the embedding size {input_dim}")
            
            # Embed the feature
            embedded_feature = embedding(x[:, i])
            print(f"Feature {i} embedded shape: {embedded_feature.shape}")
            embedded_features.append(embedded_feature)
        
        # Concatenate all embedded features
        x = torch.cat(embedded_features, dim=1)
        return x

In [13]:
# Instantiate the model
model = EmbeddingNet(embedding_sizes)

In [14]:
# Forward pass through the model to get embeddings
with torch.no_grad():  # No need to compute gradients because we re not intersted in training
    transformed_features = model(features_tensor)

Processing feature 0 with shape torch.Size([21561878]) and values: tensor([1, 1, 1,  ..., 1, 1, 1])
Feature 0: min index 0, max index 8, input_dim 9
Feature 0 embedded shape: torch.Size([21561878, 4])
Processing feature 1 with shape torch.Size([21561878]) and values: tensor([1, 2, 3,  ..., 5, 5, 5])
Feature 1: min index 0, max index 8, input_dim 9
Feature 1 embedded shape: torch.Size([21561878, 4])
Processing feature 2 with shape torch.Size([21561878]) and values: tensor([    0,     1,     2,  ..., 38298, 38297, 38299])
Feature 2: min index 0, max index 65536, input_dim 65537
Feature 2 embedded shape: torch.Size([21561878, 50])
Processing feature 3 with shape torch.Size([21561878]) and values: tensor([1, 1, 1,  ..., 2, 2, 2])
Feature 3: min index 0, max index 12, input_dim 13
Feature 3 embedded shape: torch.Size([21561878, 6])
Processing feature 4 with shape torch.Size([21561878]) and values: tensor([1, 1, 1,  ..., 0, 0, 0])
Feature 4: min index 0, max index 4, input_dim 5
Feature 4 embedded shape: torch.Size([21561878, 2])
Processing feature 5 with shape torch.Size([21561878]) and values: tensor([ 1,  2,  3,  ..., 91, 91, 91])
Feature 5: min index 0, max index 101, input_dim 102
Feature 5 embedded shape: torch.Size([21561878, 50])
Processing feature 6 with shape torch.Size([21561878]) and values: tensor([ 1,  1,  1,  ..., 91, 91, 91])
Feature 6: min index 0, max index 101, input_dim 102
Feature 6 embedded shape: torch.Size([21561878, 50])
Processing feature 7 with shape torch.Size([21561878]) and values: tensor([0, 0, 0,  ..., 0, 0, 0])
Feature 7: min index 0, max index 3301, input_dim 3302
Feature 7 embedded shape: torch.Size([21561878, 50])
Processing feature 8 with shape torch.Size([21561878]) and values: tensor([0, 0, 0,  ..., 2, 2, 2])
Feature 8: min index 0, max index 4, input_dim 5
Feature 8 embedded shape: torch.Size([21561878, 2])
Processing feature 9 with shape torch.Size([21561878]) and values: tensor([0, 0, 0,  ..., 8, 8, 8])
Feature 9: min index 0, max index 8, input_dim 9
Feature 9 embedded shape: torch.Size([21561878, 4])
Processing feature 10 with shape torch.Size([21561878]) and values: tensor([0, 1, 2,  ..., 4, 4, 4])
Feature 10: min index 0, max index 9, input_dim 10
Feature 10 embedded shape: torch.Size([21561878, 5])
Processing feature 11 with shape torch.Size([21561878]) and values: tensor([0, 0, 0,  ..., 1, 1, 1])
Feature 11: min index 0, max index 4, input_dim 5
Feature 11 embedded shape: torch.Size([21561878, 2])
Processing feature 12 with shape torch.Size([21561878]) and values: tensor([0, 0, 0,  ..., 6, 6, 6])
Feature 12: min index 0, max index 53, input_dim 54
Feature 12 embedded shape: torch.Size([21561878, 27])

In [15]:
# Convert embeddings to DataFrame
transformed_df = pd.DataFrame(transformed_features.numpy())

In [17]:
# we can see that the embedding was done perfectly no value lost
print(transformed_df.isnull().values.any())

False

In [18]:
transformed_df.head()

,0,1,2,3,4,5,6,7,8,9,...,246,247,248,249,250,251,252,253,254,255
0,-0.100433,0.831530,-0.590548,-1.275605,0.125473,-0.692483,-0.865088,-0.862070,0.440997,0.126347,...,-0.417799,2.261141,-0.539327,0.507017,-0.478598,1.407057,0.093644,-1.812366,0.689168,-0.111608
1,-0.100433,0.831530,-0.590548,-1.275605,-1.427560,-2.214863,2.212478,1.388912,-1.038465,0.176620,...,-0.417799,2.261141,-0.539327,0.507017,-0.478598,1.407057,0.093644,-1.812366,0.689168,-0.111608
2,-0.100433,0.831530,-0.590548,-1.275605,0.149928,-1.317941,-1.305659,0.559081,0.123415,-0.538616,...,-0.417799,2.261141,-0.539327,0.507017,-0.478598,1.407057,0.093644,-1.812366,0.689168,-0.111608
3,0.132813,-1.293596,1.001984,0.162317,0.793673,-0.051979,-0.763262,-0.481465,2.083035,-1.013654,...,-0.448095,1.341901,-2.118302,0.123893,-0.503124,-1.901845,-0.927061,-0.634046,-0.280395,-2.095516
4,1.051991,1.120166,1.191431,1.077091,0.793673,-0.051979,-0.763262,-0.481465,2.083035,-1.013654,...,-0.448095,1.341901,-2.118302,0.123893,-0.503124,-1.901845,-0.927061,-0.634046,-0.280395,-2.095516

In [19]:
# CHECKPOINT of transformed_df to free ram for it then to merge cont features and label from df

# Go see Prepro and Embedding 
transformed_df.to_csv('emb_net_checkpoint.csv', index=False)

In [19]:
# Now this new transformed_df is embedded but misses the phy features and Label that i both removed earlier 
# now we concat the phy features
# create df with phy features only and Label, we drop the features used earlier that are net features
phy = df.drop(columns=features)

In [20]:
print(phy.isnull().values.any())

False

In [21]:
net = transformed_df

In [21]:
# CHECKPOINT of phy df and labels

# Go see Prepro and Embedding 
phy.to_csv('phy_checkpoint.csv', index=False)

In [23]:
# we can see that the embedding is still good no value lost
# this operation is done and repeat to invistigate the sudden nan that appeared on first emb data
print(transformed_df.isnull().values.any())

False

In [24]:
# similarly we check labels and phy data and both are safe til now
print(phy.isnull().values.any())

False

In [ ]:
# Load both emb_net and phy+labels and use numpy to merge them to make it easier for ram to do store
net = pd.read_csv('emb_net_checkpoint.csv')
phy = pd.read_csv('phy_checkpoint.csv')

# it fails to load them together !!!! so we load separately , DONT RUN THIS !!

In [3]:
# Load phy and labels
phy = pd.read_csv('emb_phy/phy_checkpoint.csv')

In [4]:
# checking for nans in it just in case, RAS
print(phy.isnull().values.any())

False

In [22]:
# Transforming phy + labels to numpy 
array_phy = phy.to_numpy()

In [23]:
# Delete the pandas dataset to free memory, keep the numpys data
del phy
# notices big drop in memory usage

In [ ]:
del df

In [ ]:
# Load embedded net 
net = pd.read_csv('emb_phy/emb_net_checkpoint.csv')

In [26]:
# Transforming embedded net to numpy 
array_net = net.to_numpy()

In [27]:
del net, transformed_df

In [ ]:
# Concatenating using numpy np.concatenate

df = np.concatenate([array_net, array_phy], axis=1)

In [ ]:
# concat embedded and phy and labels
transformed_df = pd.concat([transformed_df,phy], axis=1)

In [5]:
a= transformed_df.columns
print(list(a))

NameError: name 'transformed_df' is not defined

In [115]:
transformed_df['Label'].value_counts()

Label
0.0    2687340
1.0    1457507
Name: count, dtype: int64

In [111]:
# This resulted to a df with 296 features
len(transformed_df.columns)

297

In [112]:
# Save the DataFrame to a CSV file in the Kaggle working directory
transformed_df.to_csv('super_embd.csv', index=False)

In [2]:
df = pd.read_csv('super_embd.csv')

In [4]:
df.columns = df.columns.astype(str)
# here we fixed a problem that caused index confusing during training because columlns names was int, now turned it into str

In [6]:
a= df.columns
print(list(a))

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '121', '122', '123', '124', '125', '126', '127', '128', '129', '130', '131', '132', '133', '134', '135', '136', '137', '138', '139', '140', '141', '142', '143', '144', '145', '146', '147', '148', '149', '150', '151', '152', '153', '154', '155', '156', '157', '158', '159', '160', '161', '162', '163', '164', '165', '166', '167', '168', '169', '170', '171', '172', '173', '174', '175', '176', '177', '178', '179', '180', '181', '182', '183', '184', '185', '186', '187', '188', '189', '190', '191', '192', '193', '194', '195', '196', '197', '198', '199', '200', '201', '202', '203', '204', '205', '206', '207', '208', '209', '210', '211', '212', '213', '214', '215', '216', '217', '218', '219', '220', '221', '222', '223', '224', '225', '226', '227', '228', '229', '230', '231', '232', '233', '234', '235', '236', '237', '238', '239', '240', '241', '242', '243', '244', '245', '246', '247', '248', '249', '250', '251', '252', '253', '254', '255', 'Tank_1', 'Tank_2', 'Tank_3', 'Tank_4', 'Tank_5', 'Tank_6', 'Tank_7', 'Tank_8', 'Pump_1', 'Pump_2', 'Pump_3', 'Pump_4', 'Pump_5', 'Pump_6', 'Flow_sensor_1', 'Flow_sensor_2', 'Flow_sensor_3', 'Flow_sensor_4', 'Valv_1', 'Valv_2', 'Valv_3', 'Valv_4', 'Valv_5', 'Valv_6', 'Valv_7', 'Valv_8', 'Valv_9', 'Valv_10', 'Valv_11', 'Valv_12', 'Valv_13', 'Valv_14', 'Valv_15', 'Valv_16', 'Valv_17', 'Valv_18', 'Valv_19', 'Valv_20', 'Valv_21', 'Valv_22', 'Label']

In [7]:
df.to_csv('super_embd.csv', index=False)

In [1]:
import pandas as pd
df = pd.read_csv('super_embd.csv')

In [4]:
print(df['Label'].isna().sum())

3197122

In [9]:
len(df['Label'])

7341969

In [10]:
len(df)

7341969

### 4- Checking Time compatibility for merging

#### 1 st catch

In [ ]:
# Convert all entries to datetime, parsing them flexibly
df1['Time'] = pd.to_datetime(df1['Time'], errors='coerce')

# Format all datetime objects to a uniform string format, including microseconds
df1['Formatted_Time'] = df1['Time'].dt.strftime('%Y-%m-%d %H:%M:%S.%f')

# If you want to truncate the microseconds where they are not originally present:
df1['Formatted_Time'] = df1['Formatted_Time'].apply(lambda x: x.rstrip('0').rstrip('.') if '.' in x else x)

print(df1['Formatted_Time'])

In [14]:
df1['Time'] = pd.to_datetime(df1['Time'])  # Convert to datetime if not already
df1['Time_seconds'] = df1['Time'].dt.floor('S')  # Floor to nearest second

# Count unique seconds
unique_seconds_count = df1['Time_seconds'].nunique()

print("There are", unique_seconds_count, "unique seconds in the Time column.")

There are 2420 unique seconds in the Time column.

In [ ]:
# phy1 reset button
df_phy1 = pd.read_csv('Physical_dataset/phy_att_1.csv', encoding='utf-16', delimiter='\t')

In [22]:
len(df_phy1)

2420

In [23]:
print(df1['Time'].iloc[0])
print(df1['Time'].iloc[-1])

2021-04-09 18:23:28.385003
2021-04-09 19:03:47.661291

In [24]:
print(df_phy1['Time'].iloc[0])
print(df_phy1['Time'].iloc[-1])

09/04/2021 18:23:28
09/04/2021 19:03:47

#### 2 nd catch

In [60]:
df = pd.read_csv('/kaggle/input/remainder-net/attack_2.csv')

In [ ]:
# Convert all entries to datetime, parsing them flexibly
df2['Time'] = pd.to_datetime(df2['Time'], errors='coerce')

# Format all datetime objects to a uniform string format, including microseconds
df2['Formatted_Time'] = df2['Time'].dt.strftime('%Y-%m-%d %H:%M:%S.%f')

# If you want to truncate the microseconds where they are not originally present:
df2['Formatted_Time'] = df2['Formatted_Time'].apply(lambda x: x.rstrip('0').rstrip('.') if '.' in x else x)

print(df['Formatted_Time'])

In [26]:
df2['Time'] = pd.to_datetime(df2['Time'])  # Convert to datetime if not already
df2['Time_seconds'] = df2['Time'].dt.floor('S')  # Floor to nearest second

# Count unique seconds
unique_seconds_count = df2['Time_seconds'].nunique()

print("There are", unique_seconds_count, "unique seconds in the Time column.")

There are 2096 unique seconds in the Time column.

In [71]:
# phy2 reset button
df_phy2 = pd.read_csv('Physical_dataset/phy_att_2.csv', encoding='utf-16', delimiter='\t')

In [27]:
len(df_phy2)

# we notice here a  delay of 8, !!!!!! not explainable because there is only a delay of 7 rows which is explainable under because phy_df has 7 seconds before 12 and 2 second after 16 
# compared to df which gives us 7+2 = 9   then once second must be missing inside the net df find it and delete it from phy
# and thats what we will be doing al this time deleting and adjusting rows in phy to suit net before any replication

2104

In [28]:
print(df2['Time'].iloc[0])
print(df2['Time'].iloc[-1])

2021-04-19 15:37:19.989214
2021-04-19 16:12:14.167723

In [29]:
print(df_phy2['Time'].iloc[0])
print(df_phy2['Time'].iloc[-1])

19/04/2021 15:37:12
19/04/2021 16:12:16

In [31]:
df_phy2 = df_phy2.iloc[6:-2]

In [32]:
len(df_phy2) # problem solved DONE

2096

In [33]:
print(df_phy2['Time'].iloc[0])
print(df_phy2['Time'].iloc[-1])

# we notice that the range got settled here like network data

19/04/2021 15:37:19
19/04/2021 16:12:14

In [173]:
# fixing little issue with label name from Lable_n to Label_n

df_phy2 = df_phy2.rename(columns={'Lable_n' : 'Label_n'})

#### 3 rd catch

In [35]:
df = pd.read_csv('/kaggle/input/remainder-net/attack_3.csv')

In [ ]:
# Convert all entries to datetime, parsing them flexibly
df3['Time'] = pd.to_datetime(df3['Time'], errors='coerce')

# Format all datetime objects to a uniform string format, including microseconds
df3['Formatted_Time'] = df3['Time'].dt.strftime('%Y-%m-%d %H:%M:%S.%f')

# If you want to truncate the microseconds where they are not originally present:
df3['Formatted_Time'] = df3['Formatted_Time'].apply(lambda x: x.rstrip('0').rstrip('.') if '.' in x else x)

print(df3['Formatted_Time'])

In [54]:
df3['Time'] = pd.to_datetime(df3['Time'])  # Convert to datetime if not already
df3['Time_seconds'] = df3['Time'].dt.floor('S')  # Floor to nearest second

# Count unique seconds
unique_seconds_count = df3['Time_seconds'].nunique()

print("There are", unique_seconds_count, "unique seconds in the Time column.")

There are 1252 unique seconds in the Time column.

In [40]:
# phy3 reset button
df_phy3 = pd.read_csv('Physical_dataset/phy_att_3.csv', encoding='utf-16', delimiter='\t')

In [55]:
len(df_phy3)

# we notice 2 delay, easy one to fix because there is only a delay of 2 rows which is explainable under because phy_df has one second before 12 and one second after 05 
# compared to df

1254

In [56]:
print(df3['Time'].iloc[0])
print(df3['Time'].iloc[-1])

2021-04-09 19:42:13.484804
2021-04-09 20:03:04.790765

In [57]:
print(df_phy3['Time'].iloc[0])
print(df_phy3['Time'].iloc[-1])

09/04/2021 19:42:12
09/04/2021 20:03:05

In [58]:
df_phy3 = df_phy3.iloc[1:-1]

In [59]:
len(df_phy3) # problem solved DONE

1252

In [60]:
print(df_phy3['Time'].iloc[0])
print(df_phy3['Time'].iloc[-1])

# we notice that the range got settled here like network data

09/04/2021 19:42:13
09/04/2021 20:03:04

#### 4 th catch

In [46]:
df = pd.read_csv('/kaggle/input/remainder-net/attack_4.csv')

In [ ]:
# Convert all entries to datetime, parsing them flexibly
df4['Time'] = pd.to_datetime(df4['Time'], errors='coerce')

# Format all datetime objects to a uniform string format, including microseconds
df4['Formatted_Time'] = df4['Time'].dt.strftime('%Y-%m-%d %H:%M:%S.%f')

# If you want to truncate the microseconds where they are not originally present:
df4['Formatted_Time'] = df4['Formatted_Time'].apply(lambda x: x.rstrip('0').rstrip('.') if '.' in x else x)

print(df4['Formatted_Time'])

In [68]:
df4['Time'] = pd.to_datetime(df4['Time'])  # Convert to datetime if not already
df4['Time_seconds'] = df4['Time'].dt.floor('S')  # Floor to nearest second

# Count unique seconds
unique_seconds_count = df4['Time_seconds'].nunique()

print("There are", unique_seconds_count, "unique seconds in the Time column.")

There are 1711 unique seconds in the Time column.

In [ ]:
# phy4 reset button
df_phy4 = pd.read_csv('Physical_dataset/phy_att_4.csv')

In [70]:
len(df_phy4)

# we notice here a  delay of 6, explainable because there is only a delay of 6 rows which is explainable under because phy_df has 7 seconds before 18 and 1 second before 54 
# compared to df which gives us 7-1 = 6

1717

In [71]:
print(df4['Time'].iloc[0])
print(df4['Time'].iloc[-1])

2022-02-21 14:45:25.454111
2022-02-21 15:13:55.070978

In [72]:
print(df_phy4['Time'].iloc[0])
print(df_phy4['Time'].iloc[-1])

21/02/2022 14:45:18
21/02/2022 15:13:54

In [73]:
df_phy4 = df_phy4.iloc[7:]

In [74]:
len(df_phy4) # problem not solved PROBLEM A WHOLE SET OF SECOND IN NET SHOULD BE DELETED

1710

In [75]:
print(df_phy4['Time'].iloc[0])
print(df_phy4['Time'].iloc[-1])

# we notice that the range didnt get settled here like network data

21/02/2022 14:45:25
21/02/2022 15:13:54

In [81]:
# here we mentionned the extra second we want it to remove of course all the sniffs done within that specific second will be removed too
net_sec_remove = pd.to_datetime('2022-02-21 15:13:55')

In [85]:
# now we remove all rows of that 55 th extra second in network df4
df4 = df4[~(df4['Time'].dt.floor('S') == net_sec_remove)]

In [86]:
print(df4['Time'].iloc[0])
print(df4['Time'].iloc[-1])

2022-02-21 14:45:25.454111
2022-02-21 15:13:54.997799

In [87]:
# as you can see now problem solved
len(df_phy4)

1710

In [88]:
df4['Time'] = pd.to_datetime(df4['Time'])  # Convert to datetime if not already
df4['Time_seconds'] = df4['Time'].dt.floor('S')  # Floor to nearest second

# Count unique seconds
unique_seconds_count = df4['Time_seconds'].nunique()

print("There are", unique_seconds_count, "unique seconds in the Time column.")

There are 1710 unique seconds in the Time column.

/tmp/ipykernel_123618/3868628142.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['Time'] = pd.to_datetime(df4['Time'])  # Convert to datetime if not already
/tmp/ipykernel_123618/3868628142.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['Time_seconds'] = df4['Time'].dt.floor('S')  # Floor to nearest second

### Merging test

In [93]:
def align_and_merge(net_df, phy_df):
    
    # Truncate time to the nearest second
    phy_df['Time_truncated'] = phy_df['Time'].dt.floor('S')
    net_df['Time_truncated'] = net_df['Time'].dt.floor('S')
    # Count how many entries in net_df for each second
    counts_per_second = net_df.groupby('Time_truncated').size()
    # Map the counts to phy_df based on the truncated time
    phy_df['repetitions'] = phy_df['Time_truncated'].map(counts_per_second)
    # Ensure all repetition numbers are integers
    phy_df['repetitions'] = phy_df['repetitions'].astype(int)
    # Repeat indices according to the number of repetitions needed
    repeated_indices = np.repeat(phy_df.index, phy_df['repetitions'])
    # Create the new DataFrame with repeated rows
    result_phy_df = phy_df.loc[repeated_indices].reset_index(drop=True)
    # Merge the expanded result_phy_df with net_df on 'Time_truncated'
    result_df = pd.merge(result_phy_df, net_df, on='Time_truncated', how='inner')
    return result_df

In [95]:
def align_and_merge(net_df, phy_df):
    # Make sure Time is correctly formatted
    phy_df['Time'] = pd.to_datetime(phy_df['Time'], errors='coerce')
    net_df['Time'] = pd.to_datetime(net_df['Time'], errors='coerce')
    
    # Truncate time to the nearest second
    phy_df['Time_truncated'] = phy_df['Time'].dt.floor('S')
    net_df['Time_truncated'] = net_df['Time'].dt.floor('S')
    
    # Count how many entries in net_df for each second
    counts_per_second = net_df.groupby('Time_truncated').size()
    
    # Create the list of coefficients
    list_coeff = list(counts_per_second)
    
    # Repeat indices according to list_coeff
    repeated_indices = np.repeat(phy_df.index, list_coeff)
    
    # Create the new DataFrame with repeated rows
    result_phy_df = phy_df.loc[repeated_indices].reset_index(drop=True)

    return result_phy_df

In [110]:
def trimming_net_df(net_df , phy_df):
    # get rid of extra rows in net_df that creates inbalance in merging
    rows_2_keep = net_df.index.isin(phy_df.index)
    net_df = net_df[rows_2_keep]
    return net_df

In [145]:
phuper1 = align_and_merge(df1,df_phy1)

In [114]:
nuper1 = trimming_net_df(df1, phuper1)

In [146]:
len(phuper1)

5527403

In [116]:
len(nuper1)

5527403

In [147]:
# We drop Time because we wont use it it will be replaced by net Time and drop last 3 cols generated during replication
phuper1 = phuper1.iloc[:, 1:-3]

In [148]:
phuper1.head()

,Tank_1,Tank_2,Tank_3,Tank_4,Tank_5,Tank_6,Tank_7,Tank_8,Pump_1,Pump_2,...,Valv_15,Valv_16,Valv_17,Valv_18,Valv_19,Valv_20,Valv_21,Valv_22,Label_n,Label
0,0,0,0,0,0,0,0,0,False,False,...,False,False,False,False,False,False,False,False,0,normal
1,0,0,0,0,0,0,0,0,False,False,...,False,False,False,False,False,False,False,False,0,normal
2,0,0,0,0,0,0,0,0,False,False,...,False,False,False,False,False,False,False,False,0,normal
3,0,0,0,0,0,0,0,0,False,False,...,False,False,False,False,False,False,False,False,0,normal
4,0,0,0,0,0,0,0,0,False,False,...,False,False,False,False,False,False,False,False,0,normal

In [128]:
# drop last 4 cols generated during replication
nuper1 = nuper1.iloc[:, :-4]

In [129]:
nuper1.head()

,Time,mac_s,mac_d,ip_s,ip_d,sport,dport,proto,flags,size,modbus_fn,n_pkt_src,n_pkt_dst,modbus_response,label_n,label
0,2021-04-09 18:23:28.385003,74:46:a0:bd:a7:1b,0a:fe:ec:47:74:fb,84.3.251.20,84.3.251.102,56667.0,502.0,Modbus,11000.0,66,Read Coils Request,0.0,0.0,NaN,0,normal
1,2021-04-09 18:23:28.385005,74:46:a0:bd:a7:1b,e6:3f:ac:c9:a8:8c,84.3.251.20,84.3.251.101,56666.0,502.0,Modbus,11000.0,66,Read Coils Request,1.0,0.0,NaN,0,normal
2,2021-04-09 18:23:28.385006,74:46:a0:bd:a7:1b,fa:00:bc:90:d7:fa,84.3.251.20,84.3.251.103,56668.0,502.0,Modbus,11000.0,66,Read Coils Request,2.0,0.0,NaN,0,normal
3,2021-04-09 18:23:28.385484,0a:fe:ec:47:74:fb,74:46:a0:bd:a7:1b,84.3.251.102,84.3.251.20,502.0,56667.0,Modbus,11000.0,64,Read Coils Response,0.0,0.0,[0],0,normal
4,2021-04-09 18:23:28.385486,fa:00:bc:90:d7:fa,74:46:a0:bd:a7:1b,84.3.251.103,84.3.251.20,502.0,56668.0,Modbus,11000.0,64,Read Coils Response,0.0,1.0,[0],0,normal

In [149]:
# No that everything is setup and ready we will merge 
super1 = pd.merge(nuper1, phuper1, left_index=True, right_index=True, how='inner')

In [154]:
# Clean column names by removing spaces that will later create errors in calls
super1.columns = super1.columns.str.replace(' ', '')

In [156]:
super1 = super1.drop(['label','Label'],axis = 1)

In [157]:
super1.columns

Index(['Time', 'mac_s', 'mac_d', 'ip_s', 'ip_d', 'sport', 'dport', 'proto',
       'flags', 'size', 'modbus_fn', 'n_pkt_src', 'n_pkt_dst',
       'modbus_response', 'label_n', 'Tank_1', 'Tank_2', 'Tank_3', 'Tank_4',
       'Tank_5', 'Tank_6', 'Tank_7', 'Tank_8', 'Pump_1', 'Pump_2', 'Pump_3',
       'Pump_4', 'Pump_5', 'Pump_6', 'Flow_sensor_1', 'Flow_sensor_2',
       'Flow_sensor_3', 'Flow_sensor_4', 'Valv_1', 'Valv_2', 'Valv_3',
       'Valv_4', 'Valv_5', 'Valv_6', 'Valv_7', 'Valv_8', 'Valv_9', 'Valv_10',
       'Valv_11', 'Valv_12', 'Valv_13', 'Valv_14', 'Valv_15', 'Valv_16',
       'Valv_17', 'Valv_18', 'Valv_19', 'Valv_20', 'Valv_21', 'Valv_22',
       'Label_n'],
      dtype='object')

In [164]:
# Here we compute the number of times the merge didnt agree on a labelisation 0/1
count= (super1['label_n'] != super1['Label_n']).sum()

In [163]:
err_perc = (count * 100) / len(super1)
err_perc

0.26728646346213586

Here we notice the error or discrepancy which is only 0.26 % during merging in this first super set

Now that we understood concept we process and merge rest directly

In [174]:
phuper2 = align_and_merge(df2,df_phy2)
nuper2 = trimming_net_df(df2, phuper2)


phuper2 = phuper2.iloc[:, 1:-1]

nuper2 = nuper2.iloc[:, :-3]

super2 = pd.merge(nuper2, phuper2, left_index=True, right_index=True, how='inner')

super2.columns = super2.columns.str.replace(' ', '')

super2 = super2.drop(['label','Label'],axis = 1)

count2= (super2['label_n'] != super2['Label_n']).sum()

err_perc2 = (count2 * 100) / len(super2)
err_perc2

0.5449401158957148

In [175]:
phuper3 = align_and_merge(df3,df_phy3)
nuper3 = trimming_net_df(df3, phuper3)


phuper3 = phuper3.iloc[:, 1:-1]

nuper3 = nuper3.iloc[:, :-3]

super3 = pd.merge(nuper3, phuper3, left_index=True, right_index=True, how='inner')

super3.columns = super3.columns.str.replace(' ', '')

super3 = super3.drop(['label','Label'],axis = 1)

count3= (super3['label_n'] != super3['Label_n']).sum()

err_perc3 = (count3 * 100) / len(super3)
err_perc3

0.274437359915668

In [184]:
phuper4 = align_and_merge(df4,df_phy4)
nuper4 = trimming_net_df(df4, phuper4)


phuper4 = phuper4.iloc[:, 1:-1]

nuper4 = nuper4.iloc[:, :-3]

super4 = pd.merge(nuper4, phuper4, left_index=True, right_index=True, how='inner')

super4.columns = super4.columns.str.replace(' ', '')

super4 = super4.drop(['label','Label'],axis = 1)

count4 = (super4['label_n'] != super4['Label_n']).sum()

err_perc4 = (count4 * 100) / len(super4)
err_perc4

5.032975346670749

As you can witness those are the error percentages by acquisition :
- 1 : 0.26728646346213586
- 2 : 0.5449401158957148
- 3 : 0.274437359915668
- 4 : 5.032975346670749

Now we move to merging labels with or operator to consolidate attack detection, because as mentionned in original paper some attacks wont affect network process and viseversa

In [187]:
super1['Label'] = (( super1['label_n'] == 1) | ( super1['Label_n'] == 1)).astype(int)

In [189]:
super2['Label'] = (( super2['label_n'] == 1) | ( super2['Label_n'] == 1)).astype(int)

In [190]:
super3['Label'] = (( super3['label_n'] == 1) | ( super3['Label_n'] == 1)).astype(int)

In [191]:
super4['Label'] = (( super4['label_n'] == 1) | ( super4['Label_n'] == 1)).astype(int)

In [192]:
super1 = super1.drop(['label_n','Label_n'], axis = 1)
super2 = super2.drop(['label_n','Label_n'], axis = 1)
super3 = super3.drop(['label_n','Label_n'], axis = 1)
super4 = super4.drop(['label_n','Label_n'], axis = 1)

now we save them merged 4 supers

In [197]:
super1.to_csv('new_supers/super1.csv', index=False)
super2.to_csv('new_supers/super2.csv', index=False)
super3.to_csv('new_supers/super3.csv', index=False)
super4.to_csv('new_supers/super4.csv', index=False)

DONE SUCCESSFULLY

Next merge the 4 sups (4-2-1-3) in this order because it is order of acquisition, and proceed to embedding

In [3]:
# Concat the 4 supers following the acquisition time order

sup1 = pd.read_csv('new_supers/super1.csv')
sup2 = pd.read_csv('new_supers/super2.csv')
sup3 = pd.read_csv('new_supers/super3.csv')
sup4 = pd.read_csv('new_supers/super4.csv')

In [4]:
# we concat following the time order
df = pd.concat([sup1, sup3, sup2, sup4], ignore_index=True)

In [5]:
print(df['Label'].isna().sum())

0

In [9]:
# no use for Time for us anymore because all packets are in order of chronology
df = df.drop(['Time'], axis = 1)

In [6]:
len(df)

22071868

In [7]:
# Here we drop duplicates knowing that we have large ammount of data per row witth merging of phy data so we get rid of redundancy
df = df.drop_duplicates()

# since ics is a  cyclical process if i drop duplicates before dropping time this will reduce my dataset distingutively

In [8]:
len(df)
# here we notice a drastic drop in packets from 22 Millions to 4 Millions when dropping ddupli after dropping time thats why we reverse
# and end up with 21 M data points

21561878

In [21]:
# Iterate over each feature to print the number of unique values and the unique values themselves
for column in df.columns:
    unique_count = df[column].nunique(dropna=False)  # Set dropna=False to include NaN in the count if present
    unique_values = df[column].unique()
    
    print(f"Feature: {column}")
    print(f"Number of Unique Values: {unique_count}")
    print(f"Unique Values: {unique_values}\n")

Feature: Time
Number of Unique Values: 20546717
Unique Values: ['2021-04-09 18:23:28.385003' '2021-04-09 18:23:28.385005'
 '2021-04-09 18:23:28.385006' ... '2022-02-21 15:13:54.984002'
 '2022-02-21 15:13:54.987165' '2022-02-21 15:13:54.990367']

Feature: mac_s
Number of Unique Values: 9
Unique Values: ['74:46:a0:bd:a7:1b' '0a:fe:ec:47:74:fb' 'fa:00:bc:90:d7:fa'
 'e6:3f:ac:c9:a8:8c' '00:80:f4:03:fb:12' 'fe:bb:16:7b:c3:27'
 '4a:35:83:e0:3d:a4' '00:0c:29:47:8c:22' '00:0c:29:47:8c:0e']

Feature: mac_d
Number of Unique Values: 10
Unique Values: ['0a:fe:ec:47:74:fb' 'e6:3f:ac:c9:a8:8c' 'fa:00:bc:90:d7:fa'
 '74:46:a0:bd:a7:1b' '00:80:f4:03:fb:12' 'fe:bb:16:7b:c3:27'
 '4a:35:83:e0:3d:a4' 'ff:ff:ff:ff:ff:ff' '00:0c:29:47:8c:22'
 '00:0c:29:47:8c:0e']

Feature: ip_s
Number of Unique Values: 9
Unique Values: ['84.3.251.20' '84.3.251.102' '84.3.251.103' '84.3.251.101' '84.3.251.18'
 '84.3.251.105' '84.3.251.104' nan '84.3.251.110']

Feature: ip_d
Number of Unique Values: 9
Unique Values: ['84.3.251.102' '84.3.251.101' '84.3.251.103' '84.3.251.20' '84.3.251.18'
 '84.3.251.105' '84.3.251.104' nan '84.3.251.110']

Feature: sport
Number of Unique Values: 65537
Unique Values: [56667. 56666. 56668. ...  1129.  1130.  1131.]

Feature: dport
Number of Unique Values: 18313
Unique Values: [  502. 56667. 56668. ... 16643. 16644. 16645.]

Feature: proto
Number of Unique Values: 5
Unique Values: ['Modbus' 'TCP' 'ARP' 'ICMP' 'IP']

Feature: flags
Number of Unique Values: 13
Unique Values: [1.100000e+04 1.000000e+01 1.001000e+04 1.000000e+04 1.000100e+04
 1.010000e+04 1.000000e+02          nan 1.100001e+07 1.100100e+04
 1.000000e+00 1.010010e+05 0.000000e+00]

Feature: size
Number of Unique Values: 54
Unique Values: [  66   64   65   74   78   77   60 1514 1433   62  590   70   82  109
   68   71   80   73  130   81   95  100   69  165   86  120   84  151
  122   92  133   88   87  104  146  115  144  173  129  316  317   83
   93  113  218  116  112  149  546   67   99  117  153   91]

Feature: modbus_fn
Number of Unique Values: 5
Unique Values: ['Read Coils Request' 'Read Coils Response' 'Read Holding Registers'
 'Read Holding Registers Response' nan]

Feature: n_pkt_src
Number of Unique Values: 102
Unique Values: [  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  nan  52.  53.  54.
  55.  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.
  69.  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.
  83.  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.
  97.  98.  99. 100.]

Feature: n_pkt_dst
Number of Unique Values: 102
Unique Values: [  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.
  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.
  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  nan  53.  54.
  55.  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.
  69.  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.
  83.  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.
  97.  98.  99. 100.]

Feature: modbus_response
Number of Unique Values: 3302
Unique Values: [nan '[0]' '[7]' ... '[2759]' '[2377]' '[2042]']

Feature: Tank_1
Number of Unique Values: 1796
Unique Values: [  0  54 162 ... 315 285 143]

Feature: Tank_2
Number of Unique Values: 1770
Unique Values: [  0  10  95 ... 311 563 651]

Feature: Tank_3
Number of Unique Values: 1681
Unique Values: [  0  18  94 ... 861 549 477]

Feature: Tank_4
Number of Unique Values: 1099
Unique Values: [  0  25  32 ... 458 842 909]

Feature: Tank_5
Number of Unique Values: 834
Unique Values: [  0  31  69 113 117 144 174 173 200 207 237 250 268 269 291 304 323 331
 336 360 362 374 375 401 414 437 444 452 471 478 495 516 515 522 531 546
 577 578 581 608 612 618 637 653 667 672 695 707 716 715 737 751 754 777
 780 797 811 818 812 808 803 799 795 790 787 782 778 772 768 764 759 748
 745 740 736 731 727 722 718 712 708 703 699 690 686 681 676 673 664 660
 655 651 646 643 638 634 628 625 623 616 613 609 604 600 597 592 588 584
 579 575 571 567 562 558 553 550 544 541 537 532 528 523 520 511 506 502
 499 493 491 486 482 477 474 468 465 461 457 447 443 439 435 430 426 422
 418 413 409 405 399 397 391 388 382 379 370 366 361 357 351 347 342 338
 335 329 326 321 316 311 307 302 297 292 288 284 278 273 264 258 254 248
 244 240 233 229 222 218 211 195 190 183 178 171 166 158 152 139 133 124
 107  99  87  77  61  47  29  18  12   8   7   6   4   2   1  26  80 114
 119 167 202 221 249 280 287 306 322 327 348 356 385 416 431 466 480 527
 552 587 589 633 645 665 687 693 706 713 753 765 758 767 805 814 825 824
 822 816 810 806 804 798 796 781 771 769 756 747 741 738 732 729 724 720
 710 702 698 689 684 677 668 663 659 652 647 644 641 636 632 627 624 619
 611 603 599 595 591 586 582 574 570 564 561 545 542 536 533 525 521 517
 513 508 501 497 492 489 484 472 469 464 460 455 440 432 427 423 419 415
 410 406 403 398 394 390 386 381 378 372 369 363 334 330 325 317 312 308
 303 299 293 290 276 271 267 261 257 251 247 242 238 232 227 223 217 212
 206 201 161 154 148 140 134 126 111 102  94  81  71  54  40  24  17   9
   5   3  35  85 121 132 157 176 197 208 263 279 298 365 393 424 448 458
 476 494 524 548 576 635 688 723 733 750 755 773 813 820 832 833 834 830
 821 817 763 725 711 680 640 615 610 607 590 569 565 540 512 504 488 479
 475 467 462 454 451 446 442 438 434 421 417 396 384 376 358 355 350 346
 340 337 332 328 319 315 310 301 282 272 265 245 239 235 225 220 214 198
 191 186 179 169 162 149 143 135 129 120 103  96  74  62  43  27  16  11
  68  95 160 320 367 387 598 622 656 704 779 792 826 809 800 791 783 774
 770 766 761 757 744 734 726 714 701 696 692 679 675 671 662 642 639 631
 626 614 606 594 573 549 529 496 470 456 450 402 364 294 289 285 270 266
 260 256 252 243 215 188 177 172 164 146 110  91  78  56  39 122 155 181
 199 219 230 313 333 383 483 530 551 572 670 717 835 827 823 819 801 793
 785 776 762 749 709 650 630 602 583 566 557 507 500 487 463 459 433 389
 380 371 341 324 283 275 255 216 210 205 194 182 175 170 163 153 131 115
 108  98  90  67  55  13  10  23 127 196 213 286 295 505 666 685 789 828
 802 752 691 683 674 661 657 629 620 617 605 580 568 560 555 543 535 526
 519 509 490 453 449 445 436 428 420 412 407 404 377 281 262 189 185 165
 159 147 141 101  93  72  42  28  36  89 151 184 411 425 514 658 678 697
 719 735 807 760 742 721 682 648 559 534 368 359 343 309  82  58  45  32
  14 168 226 353 485 775 786 669 554 538 481 274 246 193 138 100  52  38
  22  46 150 236 339 429 503 728 743 746 694 373 142  60  15 156 209 354
 784 836 837 838 829 831 654 601 593 539 518 473 392 345 318 314 277 259
 234 228 203  79  66  21 739 730 547 408 395 349 187 128  53  34 106 180
 224 585 649 621 510 352  73 563 498 400 145 125  64  51  20  37 344 788
 596 300 296  86 441 192 104  84  75  59  44  25 109 118  76 700 815 136
  30 705 556  92  19 112 137 231 794 130 123  97 305 241 204  63  50  88
  65  49  83  57 253 116]

Feature: Tank_6
Number of Unique Values: 533
Unique Values: [  0   9  16  25  29  38  46  50  58  67  72  78  86  94 100 109 116 121
 128 137 142 149 156 161 168 176 182 189 194 202 208 214 220 226 233 240
 246 252 258 266 272 277 284 290 297 304 310 316 322 329 335 342 348 355
 361 368 374 380 387 393 400 406 412 419 425 432 439 445 452 459 466 473
 479 486 493 501 507 515 521 529 536 543 550 558 565 572 580 588 597 606
 615 623 632 641 650 662 672 683 694 707 721 737 756 780 800 799 795 789
 774 766 758 751 736 727 719 703 695 687 671 663 655 639 631 614 598 582
 574 566 542 534 518 510 502 494 478 470 454 446 438 422 413 405 397 381
 373 365 357 349 333 325 317 309 293 285 261 253 245 237 229 212 204 196
 188 172 164 148 132 124 108  92  84  76  68  52  44  36  20  11   3   8
   4   6   7   5  10  13  18  15  26  39  49  43  37  14   1   2  23  30
  51  57  63  71  85  91  98 105 111 118 130 138 144 150 163 171 183 195
 200 207 213 219 225 231 238 251 257 263 270 276 283 289 295 302 308 314
 320 327 334 340 346 351 358 364 371 377 383 390 395 402 408 415 421 427
 433 440 447 448 450 437 435 434 423 411 404 403 394 392 382 367 360 362
 359 388 311 303 279 271 247 239 230 206 190 174 158 126 102  70  62  54
  12  35  41  60  74  79  88  95 101 107 115 127 134 140 146 153 159 166
 173 178 185 203 209 215 221 228 241 248 254 260 278 291 315 321 328 347
 353 372 378 384 409 416 428 441 453 460 458 456 455 443 431 420 410 407
 399 398 389 414 336 312 280 222 198 110  21  27  34  48  53  75  83  87
 141 160 191 205 211 217 223 235 255 267 273 287 300 307 341 366 391 429
 436 442 449 463 457 444 417 418 430 464 462 326 318 294 286 262 197 181
 165 133 125 117  93  77  69  61  45  17  40  73  81  99 113 120 147 154
 180 186 192 199 210 218 242 269 275 282 288 301 306 319 332 338 344 356
 363 376 426 379 375 369 345 330 298 274 250 234 201 193 177 169 145 129
  89  24  32  66 114 135 162 167 179 216 236 244 249 256 461 401 343 337
 313 305 281 265 136 104  96  64  56  59  80 155 232 354  19 103 123 184
 370 396 175 151 143 119  55  31 131 139 152 227 268 299 324 352 424 451
 385 350  42  90  97 106 112 386 187  47 467 465 122 170 331  65  33 292
 323  28 157 224 243 259  82  22 296 339 474]

Feature: Tank_7
Number of Unique Values: 102
Unique Values: [  0  16  24  40  48  64  72  88  96 112 120 136 144 160 168 184 192 209
 217 233 241 257 265 273 289 297 313 321 337 345 361 369 385 393 410 418
 426 442 450 458 466 402 377 353 329 305 281 249 225 176 128  80  32   8
  56 104 152 201 434 474 490 498 514 522 538 546 562 570 586 594 611 619
 635 643 659 667 683 691 707 715 731 739 755 763 779 787 804 812 771 747
 723 699 675 627 603 554 530 506 482 578 651 795]

Feature: Tank_8
Number of Unique Values: 493
Unique Values: [  0   8  16  24  32  40  48  56  64  72  80  88  96 104 112 120 128 136
 144 152 160 168 176 184 192 201 209 217 225 233 241 249 257 265 273 281
 289 297 305 313 321 329 337 345 353 357 365 373 375 383 384 392 393 401
 402 410 411 419 427 435 437 445 453 461 467 475 483 491 499 507 505 493
 492 490 488 486 484 482 480 479 465 456 454 451 450 448 447 444 442 441
 440 438 434 433 431 430 429 428 426 425 424 423 421 420 418 417 416 414
 413 412 409 408 407 406 405 404 403 400 399 398 397 396 395 394 391 390
 389 388 380 371 362 354 290 282 274 267 260 253 246 239 232 218 212 205
 199 186 180 174 163 157 151 146 140 135 130 125 115 110 106 101  92  84
  76  68  61  57  54  50  47  44  41  38  36  33  30  28  25  23  21  19
  17  15  13  12  10   9   7   6   5   4   3   2   1 361 369 415 464 472
 496 504 494 481 477 474 470 468 463 462 460 459 457 455 452 449 446 443
 439 366 358 349 341 333 325 317 309 301 293 285 278 270 263 256 242 235
 228 221 215 208 202 195 189 183 177 171 165 159 154 148 143 138 132 127
 122 117 108 103  98  94  90  86  81  77  73  70  66  62  59  55  52  49
  46  43  37  34  29  27  22  20  18  14  11  78 102 118 126 134 142 150
 158 166 182 190 198 206 214 222 231 247 255 271 279 287 295 303 311 319
 327 335 343 351 359 367 432  99  26  31  51  65  69  85 109 116 119 133
 139 141 149 156 161 167 169 172 173 175 179 181 185 187 194 196 197 204
 207 210 211 213 216 220 224 226 227 230 234 236 237 240 243 244 245 219
 200 193 147 131 121 111  97  93  58  42  39 370 378 386 497 495 489 487
 485 478 476 473 471 469 466 458 436 387 352 344 336 296 288 266 258 251
 191 145 129 124 114 105 100  91  87  83  79  75  71  67  60  53  35 377
 385 498 506 422 360 280 203 155  95  63 368 376 304 502 500 350 342 334
 326 318 310 302 294 286 264 250 229 178 123 113  82  74 501 374 382 503
 381 223 379 363 346 298 275 107 252 268 276 284 292 300 308 316 324 332
 340 348 356 364 372 355 338 330 322 314 306 283 261  45 347 323 331 339
 164 188 269 277 153 162 170]

Feature: Pump_1
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Pump_2
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Pump_3
Number of Unique Values: 1
Unique Values: [False]

Feature: Pump_4
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Pump_5
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Pump_6
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Flow_sensor_1
Number of Unique Values: 3
Unique Values: [   0 4000  100]

Feature: Flow_sensor_2
Number of Unique Values: 2
Unique Values: [   0 4000]

Feature: Flow_sensor_3
Number of Unique Values: 1
Unique Values: [0]

Feature: Flow_sensor_4
Number of Unique Values: 1343
Unique Values: [   0 4782 4772 ... 2042 1898 1706]

Feature: Valv_1
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_2
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_3
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_4
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_5
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_6
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_7
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_8
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_9
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_10
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_11
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_12
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_13
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_14
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_15
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_16
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_17
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_18
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_19
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_20
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Valv_21
Number of Unique Values: 1
Unique Values: [False]

Feature: Valv_22
Number of Unique Values: 2
Unique Values: [False  True]

Feature: Label
Number of Unique Values: 2
Unique Values: [0 1]

In [10]:
# Go see Prepro and Embedding 
df.to_csv('super.csv', index=False)

# II / Model

### 1- First Test Vanilla NN

In [2]:
df = transformed_df

NameError: name 'transformed_df' is not defined

In [167]:
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [168]:
# Function to split
def preprocess_data(df):
    # Separate features and labels
    X = df.drop(columns=['label']).values
    y = df['label'].values
    
    # Split the data into training and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    return X_train, X_test, y_train, y_test

In [169]:
# Create tensors to feed model
def create_tensors(X_train, X_test, y_train, y_test):
    # Convert to PyTorch tensors
    X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
    X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
    y_train_tensor = torch.tensor(y_train, dtype=torch.long)
    y_test_tensor = torch.tensor(y_test, dtype=torch.long)
    
    return X_train_tensor, X_test_tensor, y_train_tensor, y_test_tensor

In [170]:
# Basic vanilla Neural Network
class DeeperNN(nn.Module):
    def __init__(self, input_dim):
        super(DeeperNN, self).__init__()
        self.fc1 = nn.Linear(input_dim, 512)
        self.bn1 = nn.BatchNorm1d(512)
        self.fc2 = nn.Linear(512, 256)
        self.bn2 = nn.BatchNorm1d(256)
        self.fc3 = nn.Linear(256, 128)
        self.bn3 = nn.BatchNorm1d(128)
        self.fc4 = nn.Linear(128, 64)
        self.bn4 = nn.BatchNorm1d(64)
        self.fc5 = nn.Linear(64, 2)  # for binary classification
        self.dropout = nn.Dropout(p=0.5)

    def forward(self, x):
        x = torch.relu(self.bn1(self.fc1(x)))
        x = self.dropout(x)
        x = torch.relu(self.bn2(self.fc2(x)))
        x = self.dropout(x)
        x = torch.relu(self.bn3(self.fc3(x)))
        x = self.dropout(x)
        x = torch.relu(self.bn4(self.fc4(x)))
        x = self.fc5(x)
        return x

In [171]:
# Classical training function using Cross entropy loss and adam
def train_model(model, X_train_tensor, y_train_tensor, num_epochs=20, learning_rate=0.001):
    # Define loss function and optimizer
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=learning_rate)
    
    # Training loop
    for epoch in range(num_epochs):
        model.train()
        optimizer.zero_grad()
        outputs = model(X_train_tensor)
        loss = criterion(outputs, y_train_tensor)
        loss.backward()
        optimizer.step()
        print(f'Epoch {epoch+1}/{num_epochs}, Loss: {loss.item()}')

In [172]:
# Eval function
def evaluate_model(model, X_test_tensor, y_test_tensor):
    # Evaluate the model
    model.eval()
    with torch.no_grad():
        outputs = model(X_test_tensor)
        _, predicted = torch.max(outputs, 1)
        accuracy = (predicted == y_test_tensor).sum().item() / y_test_tensor.size(0)
    return accuracy

In [1]:
# Preprocess data
X_train, X_test, y_train, y_test = preprocess_data(df)

# Create tensors
X_train_tensor, X_test_tensor, y_train_tensor, y_test_tensor = create_tensors(X_train, X_test, y_train, y_test)

# Define and train the model
input_dim = X_train_tensor.shape[1]
model = DeeperNN(input_dim)
train_model(model, X_train_tensor, y_train_tensor)

# Evaluate the model
accuracy = evaluate_model(model, X_test_tensor, y_test_tensor)
print(f'Accuracy on test set: {accuracy * 100:.2f}%')

NameError: name 'preprocess_data' is not defined